import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const configDir = dirname(fileURLToPath(import.meta.url));

/** Shared path aliases — must stay in sync with tsconfig / register-aliases. */
export const aliases = {
  '@shared': resolve(configDir, './src/shared'),
  '@contracts/schemas/common': resolve(configDir, './packages/contracts/src/schemas/common.schemas'),
  '@contracts/schemas/command': resolve(configDir, './packages/contracts/src/schemas/command.schemas'),
  '@contracts/schemas/prompt-history': resolve(configDir, './packages/contracts/src/schemas/prompt-history.schemas'),
  '@contracts/schemas/workflow': resolve(configDir, './packages/contracts/src/schemas/workflow.schemas'),
  '@contracts/schemas/pause': resolve(configDir, './packages/contracts/src/schemas/pause.schemas'),
  '@contracts/schemas/instance': resolve(configDir, './packages/contracts/src/schemas/instance.schemas'),
  '@contracts/schemas/session': resolve(configDir, './packages/contracts/src/schemas/session.schemas'),
  '@contracts/schemas/provider': resolve(configDir, './packages/contracts/src/schemas/provider.schemas'),
  '@contracts/schemas/orchestration': resolve(configDir, './packages/contracts/src/schemas/orchestration.schemas'),
  '@contracts/schemas/verification': resolve(configDir, './packages/contracts/src/schemas/verification.schemas'),
  '@contracts/schemas/settings': resolve(configDir, './packages/contracts/src/schemas/settings.schemas'),
  '@contracts/schemas/file-operations': resolve(configDir, './packages/contracts/src/schemas/file-operations.schemas'),
  '@contracts/schemas/security': resolve(configDir, './packages/contracts/src/schemas/security.schemas'),
  '@contracts/schemas/observability': resolve(configDir, './packages/contracts/src/schemas/observability.schemas'),
  '@contracts/schemas/workspace-tools': resolve(configDir, './packages/contracts/src/schemas/workspace-tools.schemas'),
  '@contracts/schemas/knowledge': resolve(configDir, './packages/contracts/src/schemas/knowledge.schemas'),
  '@contracts/schemas/remote-node': resolve(configDir, './packages/contracts/src/schemas/remote-node.schemas'),
  '@contracts/schemas/plugin': resolve(configDir, './packages/contracts/src/schemas/plugin.schemas'),
  '@contracts/schemas/image': resolve(configDir, './packages/contracts/src/schemas/image.schemas'),
  '@contracts/schemas/automation': resolve(configDir, './packages/contracts/src/schemas/automation.schemas'),
  '@contracts/schemas/webhook': resolve(configDir, './packages/contracts/src/schemas/webhook.schemas'),
  '@contracts/schemas/quota': resolve(configDir, './packages/contracts/src/schemas/quota.schemas'),
  '@contracts/schemas/voice': resolve(configDir, './packages/contracts/src/schemas/voice.schemas'),
  '@contracts/schemas/browser': resolve(configDir, './packages/contracts/src/schemas/browser.schemas'),
  '@contracts/schemas/browser-unattended': resolve(configDir, './packages/contracts/src/schemas/browser-unattended.schemas'),
  '@contracts/schemas/conversation-ledger': resolve(configDir, './packages/contracts/src/schemas/conversation-ledger.schemas'),
  '@contracts/schemas/operator': resolve(configDir, './packages/contracts/src/schemas/operator.schemas'),
  '@contracts/schemas/chat': resolve(configDir, './packages/contracts/src/schemas/chat.schemas'),
  '@contracts/schemas/mcp-multi-provider': resolve(configDir, './packages/contracts/src/schemas/mcp-multi-provider.schemas'),
  '@contracts/schemas/provider-runtime-events': resolve(configDir, './packages/contracts/src/schemas/provider-runtime-events.schemas'),
  '@contracts/schemas/loop': resolve(configDir, './packages/contracts/src/schemas/loop.schemas'),
  '@contracts/schemas/loop-events': resolve(configDir, './packages/contracts/src/schemas/loop-events.schemas'),
  '@contracts/schemas/campaign': resolve(configDir, './packages/contracts/src/schemas/campaign.schemas'),
  '@contracts/schemas/doc-review': resolve(configDir, './packages/contracts/src/schemas/doc-review.schemas'),
  '@contracts/schemas/rlm-maintenance': resolve(configDir, './packages/contracts/src/schemas/rlm-maintenance.schemas'),
  '@contracts/schemas/context-evidence': resolve(configDir, './packages/contracts/src/schemas/context-evidence.schemas'),
  '@contracts/channels/automation': resolve(configDir, './packages/contracts/src/channels/automation.channels'),
  '@contracts/channels/campaign': resolve(configDir, './packages/contracts/src/channels/campaign.channels'),
  '@contracts/channels/pause': resolve(configDir, './packages/contracts/src/channels/pause.channels'),
  '@contracts/channels/voice': resolve(configDir, './packages/contracts/src/channels/voice.channels'),
  '@contracts/channels/browser': resolve(configDir, './packages/contracts/src/channels/browser.channels'),
  '@contracts/channels/conversation-ledger': resolve(configDir, './packages/contracts/src/channels/conversation-ledger.channels'),
  '@contracts/channels/operator': resolve(configDir, './packages/contracts/src/channels/operator.channels'),
  '@contracts/channels/chat': resolve(configDir, './packages/contracts/src/channels/chat.channels'),
  '@contracts/channels/loop': resolve(configDir, './packages/contracts/src/channels/loop.channels'),
  '@contracts/types/instance-events': resolve(configDir, './packages/contracts/src/types/instance-events'),
  '@contracts/types/provider-runtime-events': resolve(configDir, './packages/contracts/src/types/provider-runtime-events'),
  '@contracts/types/transport': resolve(configDir, './packages/contracts/src/types/transport.types'),
  '@contracts/types/browser': resolve(configDir, './packages/contracts/src/types/browser.types'),
  '@contracts/types/context-evidence': resolve(configDir, './packages/contracts/src/types/context-evidence.types'),
  '@contracts': resolve(configDir, './packages/contracts/src'),
  '@sdk': resolve(configDir, './packages/sdk/src'),
};
