/**
 * IPC channels for the learning subsystems: self-improvement (learning outcomes),
 * GRPO training data, specialist agents, and A/B experiment management.
 */
export const LEARNING_CHANNELS = {
  // Self-Improvement operations
  LEARNING_RECORD_OUTCOME: 'learning:record-outcome',
  LEARNING_GET_OUTCOME: 'learning:get-outcome',
  LEARNING_GET_RECENT_OUTCOMES: 'learning:get-recent-outcomes',
  LEARNING_GET_EXPERIENCE: 'learning:get-experience',
  LEARNING_GET_ALL_EXPERIENCES: 'learning:get-all-experiences',
  LEARNING_GET_INSIGHTS: 'learning:get-insights',
  LEARNING_GET_PATTERNS: 'learning:get-patterns',
  LEARNING_GET_SUGGESTIONS: 'learning:get-suggestions',
  LEARNING_GET_RECOMMENDATION: 'learning:get-recommendation',
  LEARNING_ENHANCE_PROMPT: 'learning:enhance-prompt',
  LEARNING_GET_STATS: 'learning:get-stats',
  LEARNING_GET_TASK_STATS: 'learning:get-task-stats',
  LEARNING_RATE_OUTCOME: 'learning:rate-outcome',
  LEARNING_CONFIGURE: 'learning:configure',

  // Training operations (GRPO)
  TRAINING_RECORD_OUTCOME: 'training:record-outcome',
  TRAINING_GET_STATS: 'training:get-stats',
  TRAINING_EXPORT_DATA: 'training:export-data',
  TRAINING_IMPORT_DATA: 'training:import-data',
  TRAINING_GET_TREND: 'training:get-trend',
  TRAINING_GET_TOP_STRATEGIES: 'training:get-top-strategies',
  TRAINING_CONFIGURE: 'training:configure',
  TRAINING_GET_REWARD_DATA: 'training:get-reward-data',
  TRAINING_GET_ADVANTAGE_DATA: 'training:get-advantage-data',
  TRAINING_GET_STRATEGIES: 'training:get-strategies',
  TRAINING_GET_AGENT_PERFORMANCE: 'training:get-agent-performance',
  TRAINING_GET_PATTERNS: 'training:get-patterns',
  TRAINING_GET_INSIGHTS: 'training:get-insights',
  TRAINING_APPLY_INSIGHT: 'training:apply-insight',
  TRAINING_DISMISS_INSIGHT: 'training:dismiss-insight',
  TRAINING_UPDATE_CONFIG: 'training:update-config',

  // Training event forwarding (main -> renderer)
  TRAINING_EVENT_STARTED: 'training:event:started',
  TRAINING_EVENT_COMPLETED: 'training:event:completed',
  TRAINING_EVENT_ERROR: 'training:event:error',

  // Specialist operations
  SPECIALIST_LIST: 'specialist:list',
  SPECIALIST_LIST_BUILTIN: 'specialist:list-builtin',
  SPECIALIST_LIST_CUSTOM: 'specialist:list-custom',
  SPECIALIST_GET: 'specialist:get',
  SPECIALIST_GET_BY_CATEGORY: 'specialist:get-by-category',
  SPECIALIST_ADD_CUSTOM: 'specialist:add-custom',
  SPECIALIST_UPDATE_CUSTOM: 'specialist:update-custom',
  SPECIALIST_REMOVE_CUSTOM: 'specialist:remove-custom',
  SPECIALIST_RECOMMEND: 'specialist:recommend',
  SPECIALIST_CREATE_INSTANCE: 'specialist:create-instance',
  SPECIALIST_GET_INSTANCE: 'specialist:get-instance',
  SPECIALIST_GET_ACTIVE_INSTANCES: 'specialist:get-active-instances',
  SPECIALIST_UPDATE_STATUS: 'specialist:update-status',
  SPECIALIST_ADD_FINDING: 'specialist:add-finding',
  SPECIALIST_UPDATE_METRICS: 'specialist:update-metrics',
  SPECIALIST_GET_PROMPT_ADDITION: 'specialist:get-prompt-addition',
  SPECIALIST_INSTANCE_CREATED: 'specialist:instance-created',
  SPECIALIST_INSTANCE_STATUS_CHANGED: 'specialist:instance-status-changed',
  SPECIALIST_FINDING_ADDED: 'specialist:finding-added',

  // A/B Testing operations
  AB_CREATE_EXPERIMENT: 'ab:create-experiment',
  AB_UPDATE_EXPERIMENT: 'ab:update-experiment',
  AB_DELETE_EXPERIMENT: 'ab:delete-experiment',
  AB_START_EXPERIMENT: 'ab:start-experiment',
  AB_PAUSE_EXPERIMENT: 'ab:pause-experiment',
  AB_COMPLETE_EXPERIMENT: 'ab:complete-experiment',
  AB_GET_EXPERIMENT: 'ab:get-experiment',
  AB_LIST_EXPERIMENTS: 'ab:list-experiments',
  AB_GET_VARIANT: 'ab:get-variant',
  AB_RECORD_OUTCOME: 'ab:record-outcome',
  AB_GET_RESULTS: 'ab:get-results',
  AB_GET_WINNER: 'ab:get-winner',
  AB_GET_STATS: 'ab:get-stats',
  AB_CONFIGURE: 'ab:configure',
} as const;
