/**
 * worktree-port — P7 runtime namespacing for worktree isolation.
 *
 * Worktrees isolate files, not ports. `.mise.toml` pins AIO_RENDERER_PORT=4567
 * for every directory, so two worktrees that each start the renderer (or an
 * electron smoke check) would collide on the same port. At acquire time we
 * allocate a free port per session and write it into a per-worktree
 * `.mise.local.toml` — mise's standard local-override file, which takes
 * precedence over `.mise.toml` and is gitignored — so each session's tooling
 * picks up its own port without touching the shared config.
 */

import * as net from 'net';
import * as fs from 'fs/promises';
import * as path from 'path';
import { getLogger } from '../../logging/logger';

const logger = getLogger('WorktreePort');

export const DEFAULT_RENDERER_PORT = 4567;
/** Search window above the default. 200 slots is far more than maxConcurrent. */
const DEFAULT_PORT_SPAN = 200;

/** Resolve true if nothing is listening on `port` (loopback), false otherwise. */
export function isPortFree(port: number, host = '127.0.0.1'): Promise<boolean> {
  return new Promise((resolve) => {
    const srv = net.createServer();
    srv.once('error', () => resolve(false));
    srv.once('listening', () => {
      srv.close(() => resolve(true));
    });
    try {
      srv.listen(port, host);
    } catch {
      resolve(false);
    }
  });
}

/**
 * Allocate the first free renderer port at/above `base`, skipping any port in
 * `exclude` (ports already reserved by live sibling sessions in this process).
 */
export async function allocateRendererPort(opts?: {
  base?: number;
  span?: number;
  exclude?: ReadonlySet<number>;
}): Promise<number> {
  const base = opts?.base ?? DEFAULT_RENDERER_PORT;
  const span = opts?.span ?? DEFAULT_PORT_SPAN;
  const exclude = opts?.exclude ?? new Set<number>();

  for (let port = base; port < base + span; port++) {
    if (exclude.has(port)) continue;
    if (await isPortFree(port)) return port;
  }
  throw new Error(`No free renderer port in range ${base}..${base + span - 1}`);
}

/** Build the `.mise.local.toml` override body for a given renderer port. */
export function renderMiseLocalOverride(port: number): string {
  return (
    '# Auto-generated by AIO worktree isolation (P7).\n' +
    '# Per-session renderer port so parallel renderer/smoke sessions do not\n' +
    '# collide on the shared AIO_RENDERER_PORT pinned in .mise.toml.\n' +
    '[env]\n' +
    `AIO_RENDERER_PORT = "${port}"\n`
  );
}

/**
 * Allocate a renderer port and write the per-worktree mise override. Returns the
 * allocated port. Best-effort: throws only if no port can be allocated; callers
 * should treat a throw as non-fatal to the acquire (isolation of files still holds).
 */
export async function assignWorktreeRendererPort(
  worktreePath: string,
  opts?: { base?: number; span?: number; exclude?: ReadonlySet<number> },
): Promise<number> {
  const port = await allocateRendererPort(opts);
  const file = path.join(worktreePath, '.mise.local.toml');
  await fs.writeFile(file, renderMiseLocalOverride(port), 'utf-8');
  logger.info('WorktreePort: assigned per-session renderer port', { worktreePath, port });
  return port;
}
