/**
 * AUTO-GENERATED by scripts/sync-model-catalog.ts — DO NOT EDIT BY HAND.
 *
 * Offline model-catalog snapshot captured from https://models.dev/api.json for
 * the provider namespaces this app supports (anthropic, openai, google, github-copilot).
 * Seeded into ModelsDevService at startup via `loadOfflineSnapshot()`; the live
 * fetch overwrites individual entries when it lands. Pricing is USD per 1M
 * tokens; context/output limits are token counts.
 *
 * Regenerate: `npm run sync:model-catalog`.
 */

export interface ModelsDevSnapshotEntry {
  /** models.dev provider namespace (e.g. 'anthropic'). */
  provider: string;
  /** USD per 1M input tokens. */
  input: number;
  /** USD per 1M output tokens. */
  output: number;
  /** Total context window in tokens, when published. */
  contextWindow?: number;
  /** Max output tokens in one response, when published. */
  maxOutputTokens?: number;
}

export const MODELS_DEV_SNAPSHOT: Record<string, ModelsDevSnapshotEntry> = {
  'claude-fable-5': { provider: 'anthropic', input: 10, output: 50, contextWindow: 1000000, maxOutputTokens: 128000 },
  'claude-haiku-4-5': { provider: 'anthropic', input: 1, output: 5, contextWindow: 200000, maxOutputTokens: 64000 },
  'claude-haiku-4-5-20251001': { provider: 'anthropic', input: 1, output: 5, contextWindow: 200000, maxOutputTokens: 64000 },
  'claude-opus-4-1': { provider: 'anthropic', input: 15, output: 75, contextWindow: 200000, maxOutputTokens: 32000 },
  'claude-opus-4-1-20250805': { provider: 'anthropic', input: 15, output: 75, contextWindow: 200000, maxOutputTokens: 32000 },
  'claude-opus-4-5': { provider: 'anthropic', input: 5, output: 25, contextWindow: 200000, maxOutputTokens: 64000 },
  'claude-opus-4-5-20251101': { provider: 'anthropic', input: 5, output: 25, contextWindow: 200000, maxOutputTokens: 64000 },
  'claude-opus-4-6': { provider: 'anthropic', input: 5, output: 25, contextWindow: 1000000, maxOutputTokens: 128000 },
  'claude-opus-4-7': { provider: 'anthropic', input: 5, output: 25, contextWindow: 1000000, maxOutputTokens: 128000 },
  'claude-opus-4-8': { provider: 'anthropic', input: 5, output: 25, contextWindow: 1000000, maxOutputTokens: 128000 },
  'claude-sonnet-4-5': { provider: 'anthropic', input: 3, output: 15, contextWindow: 1000000, maxOutputTokens: 64000 },
  'claude-sonnet-4-5-20250929': { provider: 'anthropic', input: 3, output: 15, contextWindow: 1000000, maxOutputTokens: 64000 },
  'claude-sonnet-4-6': { provider: 'anthropic', input: 3, output: 15, contextWindow: 1000000, maxOutputTokens: 128000 },
  'claude-sonnet-5': { provider: 'anthropic', input: 2, output: 10, contextWindow: 1000000, maxOutputTokens: 128000 },
  'claude-haiku-4.5': { provider: 'github-copilot', input: 1, output: 5, contextWindow: 200000, maxOutputTokens: 64000 },
  'claude-opus-4.5': { provider: 'github-copilot', input: 5, output: 25, contextWindow: 200000, maxOutputTokens: 32000 },
  'claude-opus-4.6': { provider: 'github-copilot', input: 5, output: 25, contextWindow: 200000, maxOutputTokens: 32000 },
  'claude-opus-4.7': { provider: 'github-copilot', input: 5, output: 25, contextWindow: 200000, maxOutputTokens: 32000 },
  'claude-opus-4.8': { provider: 'github-copilot', input: 5, output: 25, contextWindow: 200000, maxOutputTokens: 64000 },
  'claude-sonnet-4': { provider: 'github-copilot', input: 3, output: 15, contextWindow: 216000, maxOutputTokens: 16000 },
  'claude-sonnet-4.5': { provider: 'github-copilot', input: 3, output: 15, contextWindow: 200000, maxOutputTokens: 32000 },
  'claude-sonnet-4.6': { provider: 'github-copilot', input: 3, output: 15, contextWindow: 200000, maxOutputTokens: 32000 },
  'kimi-k2.7-code': { provider: 'github-copilot', input: 0.95, output: 4, contextWindow: 256000, maxOutputTokens: 32000 },
  'mai-code-1-flash-picker': { provider: 'github-copilot', input: 0.75, output: 4.5, contextWindow: 256000, maxOutputTokens: 128000 },
  'gemini-2.0-flash': { provider: 'google', input: 0.1, output: 0.4, contextWindow: 1048576, maxOutputTokens: 8192 },
  'gemini-2.0-flash-lite': { provider: 'google', input: 0.075, output: 0.3, contextWindow: 1048576, maxOutputTokens: 8192 },
  'gemini-2.5-flash': { provider: 'google', input: 0.3, output: 2.5, contextWindow: 1048576, maxOutputTokens: 65536 },
  'gemini-2.5-flash-image': { provider: 'google', input: 0.3, output: 30, contextWindow: 32768, maxOutputTokens: 32768 },
  'gemini-2.5-flash-lite': { provider: 'google', input: 0.1, output: 0.4, contextWindow: 1048576, maxOutputTokens: 65536 },
  'gemini-2.5-flash-preview-tts': { provider: 'google', input: 0.5, output: 10, contextWindow: 8192, maxOutputTokens: 16384 },
  'gemini-2.5-pro': { provider: 'google', input: 1.25, output: 10, contextWindow: 1048576, maxOutputTokens: 65536 },
  'gemini-2.5-pro-preview-tts': { provider: 'google', input: 1, output: 20, contextWindow: 8192, maxOutputTokens: 16384 },
  'gemini-3-flash-preview': { provider: 'google', input: 0.5, output: 3, contextWindow: 1048576, maxOutputTokens: 65536 },
  'gemini-3-pro-image-preview': { provider: 'google', input: 2, output: 120, contextWindow: 131072, maxOutputTokens: 32768 },
  'gemini-3-pro-preview': { provider: 'google', input: 2, output: 12, contextWindow: 1048576, maxOutputTokens: 65536 },
  'gemini-3.1-flash-image-preview': { provider: 'google', input: 0.5, output: 60, contextWindow: 65536, maxOutputTokens: 65536 },
  'gemini-3.1-flash-lite': { provider: 'google', input: 0.25, output: 1.5, contextWindow: 1048576, maxOutputTokens: 65536 },
  'gemini-3.1-flash-lite-preview': { provider: 'google', input: 0.25, output: 1.5, contextWindow: 1048576, maxOutputTokens: 65536 },
  'gemini-3.1-pro-preview': { provider: 'google', input: 2, output: 12, contextWindow: 1048576, maxOutputTokens: 65536 },
  'gemini-3.1-pro-preview-customtools': { provider: 'google', input: 2, output: 12, contextWindow: 1048576, maxOutputTokens: 65536 },
  'gemini-3.5-flash': { provider: 'google', input: 1.5, output: 9, contextWindow: 1048576, maxOutputTokens: 65536 },
  'gemini-embedding-001': { provider: 'google', input: 0.15, output: 0, contextWindow: 2048, maxOutputTokens: 1 },
  'gemini-flash-latest': { provider: 'google', input: 1.5, output: 9, contextWindow: 1048576, maxOutputTokens: 65536 },
  'gemini-flash-lite-latest': { provider: 'google', input: 0.25, output: 1.5, contextWindow: 1048576, maxOutputTokens: 65536 },
  'gemini-omni-flash-preview': { provider: 'google', input: 1.5, output: 17.5, contextWindow: 131072, maxOutputTokens: 65536 },
  'gpt-3.5-turbo': { provider: 'openai', input: 0.5, output: 1.5, contextWindow: 16385, maxOutputTokens: 4096 },
  'gpt-4': { provider: 'openai', input: 30, output: 60, contextWindow: 8192, maxOutputTokens: 8192 },
  'gpt-4-turbo': { provider: 'openai', input: 10, output: 30, contextWindow: 128000, maxOutputTokens: 4096 },
  'gpt-4.1': { provider: 'openai', input: 2, output: 8, contextWindow: 1047576, maxOutputTokens: 32768 },
  'gpt-4.1-mini': { provider: 'openai', input: 0.4, output: 1.6, contextWindow: 1047576, maxOutputTokens: 32768 },
  'gpt-4.1-nano': { provider: 'openai', input: 0.1, output: 0.4, contextWindow: 1047576, maxOutputTokens: 32768 },
  'gpt-4o': { provider: 'openai', input: 2.5, output: 10, contextWindow: 128000, maxOutputTokens: 16384 },
  'gpt-4o-2024-05-13': { provider: 'openai', input: 5, output: 15, contextWindow: 128000, maxOutputTokens: 4096 },
  'gpt-4o-2024-08-06': { provider: 'openai', input: 2.5, output: 10, contextWindow: 128000, maxOutputTokens: 16384 },
  'gpt-4o-2024-11-20': { provider: 'openai', input: 2.5, output: 10, contextWindow: 128000, maxOutputTokens: 16384 },
  'gpt-4o-mini': { provider: 'openai', input: 0.15, output: 0.6, contextWindow: 128000, maxOutputTokens: 16384 },
  'gpt-5': { provider: 'openai', input: 1.25, output: 10, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5-chat-latest': { provider: 'openai', input: 1.25, output: 10, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5-codex': { provider: 'openai', input: 1.25, output: 10, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5-mini': { provider: 'openai', input: 0.25, output: 2, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5-nano': { provider: 'openai', input: 0.05, output: 0.4, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5-pro': { provider: 'openai', input: 15, output: 120, contextWindow: 400000, maxOutputTokens: 272000 },
  'gpt-5.1': { provider: 'openai', input: 1.25, output: 10, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5.1-chat-latest': { provider: 'openai', input: 1.25, output: 10, contextWindow: 128000, maxOutputTokens: 16384 },
  'gpt-5.1-codex': { provider: 'openai', input: 1.25, output: 10, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5.1-codex-max': { provider: 'openai', input: 1.25, output: 10, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5.1-codex-mini': { provider: 'openai', input: 0.25, output: 2, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5.2': { provider: 'openai', input: 1.75, output: 14, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5.2-chat-latest': { provider: 'openai', input: 1.75, output: 14, contextWindow: 128000, maxOutputTokens: 16384 },
  'gpt-5.2-codex': { provider: 'openai', input: 1.75, output: 14, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5.2-pro': { provider: 'openai', input: 21, output: 168, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5.3-chat-latest': { provider: 'openai', input: 1.75, output: 14, contextWindow: 128000, maxOutputTokens: 16384 },
  'gpt-5.3-codex': { provider: 'openai', input: 1.75, output: 14, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5.3-codex-spark': { provider: 'openai', input: 1.75, output: 14, contextWindow: 128000, maxOutputTokens: 32000 },
  'gpt-5.4': { provider: 'openai', input: 2.5, output: 15, contextWindow: 1050000, maxOutputTokens: 128000 },
  'gpt-5.4-mini': { provider: 'openai', input: 0.75, output: 4.5, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5.4-nano': { provider: 'openai', input: 0.2, output: 1.25, contextWindow: 400000, maxOutputTokens: 128000 },
  'gpt-5.4-pro': { provider: 'openai', input: 30, output: 180, contextWindow: 1050000, maxOutputTokens: 128000 },
  'gpt-5.5': { provider: 'openai', input: 5, output: 30, contextWindow: 1050000, maxOutputTokens: 128000 },
  'gpt-5.5-pro': { provider: 'openai', input: 30, output: 180, contextWindow: 1050000, maxOutputTokens: 128000 },
  'gpt-5.6': { provider: 'openai', input: 5, output: 30, contextWindow: 1050000, maxOutputTokens: 128000 },
  'gpt-5.6-luna': { provider: 'openai', input: 1, output: 6, contextWindow: 1050000, maxOutputTokens: 128000 },
  'gpt-5.6-sol': { provider: 'openai', input: 5, output: 30, contextWindow: 1050000, maxOutputTokens: 128000 },
  'gpt-5.6-terra': { provider: 'openai', input: 2.5, output: 15, contextWindow: 1050000, maxOutputTokens: 128000 },
  'gpt-image-2': { provider: 'openai', input: 5, output: 30, contextWindow: 0, maxOutputTokens: 0 },
  'gpt-realtime-2.1': { provider: 'openai', input: 4, output: 24, contextWindow: 128000, maxOutputTokens: 32000 },
  'o1': { provider: 'openai', input: 15, output: 60, contextWindow: 200000, maxOutputTokens: 100000 },
  'o1-pro': { provider: 'openai', input: 150, output: 600, contextWindow: 200000, maxOutputTokens: 100000 },
  'o3': { provider: 'openai', input: 2, output: 8, contextWindow: 200000, maxOutputTokens: 100000 },
  'o3-deep-research': { provider: 'openai', input: 10, output: 40, contextWindow: 200000, maxOutputTokens: 100000 },
  'o3-mini': { provider: 'openai', input: 1.1, output: 4.4, contextWindow: 200000, maxOutputTokens: 100000 },
  'o3-pro': { provider: 'openai', input: 20, output: 80, contextWindow: 200000, maxOutputTokens: 100000 },
  'o4-mini': { provider: 'openai', input: 1.1, output: 4.4, contextWindow: 200000, maxOutputTokens: 100000 },
  'o4-mini-deep-research': { provider: 'openai', input: 2, output: 8, contextWindow: 200000, maxOutputTokens: 100000 },
  'text-embedding-3-large': { provider: 'openai', input: 0.13, output: 0, contextWindow: 8191, maxOutputTokens: 3072 },
  'text-embedding-3-small': { provider: 'openai', input: 0.02, output: 0, contextWindow: 8191, maxOutputTokens: 1536 },
  'text-embedding-ada-002': { provider: 'openai', input: 0.1, output: 0, contextWindow: 8192, maxOutputTokens: 1536 },
};

export const MODELS_DEV_SNAPSHOT_META = {
  source: 'https://models.dev/api.json',
  providerScope: ['anthropic', 'openai', 'google', 'github-copilot'],
  modelCount: 97,
} as const;
