/**
 * sync-model-catalog.ts  (backlog A2 / Phase 3-B)
 *
 * Regenerates the committed offline model-catalog snapshot
 * `src/main/providers/models-dev-snapshot.generated.ts` from the live
 * models.dev registry (https://models.dev/api.json).
 *
 * Why this exists
 * ---------------
 * At runtime `ModelsDevService` fetches models.dev and overlays fresh pricing +
 * context windows onto the committed `MODEL_PRICING` snapshot. But that live
 * overlay is empty until the first successful fetch each launch — and entirely
 * empty when the app runs offline. This script captures a build-time snapshot
 * that `ModelsDevService.loadOfflineSnapshot()` seeds at startup, so pricing and
 * context windows for the providers we support are correct immediately and
 * fully offline. The live fetch then overwrites individual entries when it lands.
 *
 * Scope: only the provider namespaces this app actually drives (Claude/Codex/
 * Gemini/Grok/Copilot → anthropic/openai/google/xai/github-copilot). Mirrors the
 * curated "just the useful models" philosophy of generate-cursor-models.ts and
 * keeps the generated file small enough to read in a diff. Extend
 * SUPPORTED_PROVIDERS (in sync-model-catalog.parse.ts) to widen offline coverage.
 *
 * Usage:
 *   npm run sync:model-catalog            # regenerate the snapshot in place
 *   tsx scripts/sync-model-catalog.ts --check   # CI: fail if the snapshot drifted
 *
 * `--check` is fail-soft when models.dev is unreachable (exit 0 + notice), so it
 * is safe on offline hosts. It is deliberately NOT wired into `prebuild`:
 * models.dev pricing changes on the order of days, so a hard drift gate would
 * be noisy. Run it manually to refresh the committed snapshot.
 */

import { get as httpsGet } from 'node:https';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  SUPPORTED_PROVIDERS,
  parseSnapshot,
  type SnapshotEntry,
} from './sync-model-catalog.parse';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const TARGET_FILE = resolve(SCRIPT_DIR, '../src/main/providers/models-dev-snapshot.generated.ts');
const MODELS_DEV_API_URL = 'https://models.dev/api.json';
const REQUEST_TIMEOUT_MS = 15_000;
const MAX_RESPONSE_BYTES = 32 * 1024 * 1024;

// ---------------------------------------------------------------------------
// Fetch + parse
// ---------------------------------------------------------------------------

function fetchApiJson(): Promise<string | null> {
  return new Promise((resolve) => {
    const req = httpsGet(MODELS_DEV_API_URL, (res) => {
      const status = res.statusCode ?? 0;
      if (status < 200 || status >= 300) {
        res.resume();
        resolve(null);
        return;
      }
      let size = 0;
      const chunks: Buffer[] = [];
      res.on('data', (chunk: Buffer) => {
        size += chunk.length;
        if (size > MAX_RESPONSE_BYTES) {
          req.destroy();
          resolve(null);
          return;
        }
        chunks.push(chunk);
      });
      res.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    });
    req.setTimeout(REQUEST_TIMEOUT_MS, () => {
      req.destroy();
      resolve(null);
    });
    req.on('error', () => resolve(null));
  });
}

// ---------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------

function renderEntry(id: string, e: SnapshotEntry): string {
  const parts = [`provider: '${e.provider}'`, `input: ${e.input}`, `output: ${e.output}`];
  if (e.contextWindow !== undefined) parts.push(`contextWindow: ${e.contextWindow}`);
  if (e.maxOutputTokens !== undefined) parts.push(`maxOutputTokens: ${e.maxOutputTokens}`);
  // Model ids never contain a single quote, so single-quoting is safe and
  // matches the value style / repo lint config (avoids a double-quote warning).
  return `  '${id}': { ${parts.join(', ')} },`;
}

function render(snapshot: Record<string, SnapshotEntry>): string {
  // Deterministic order: provider, then model id, so diffs are stable.
  const ids = Object.keys(snapshot).sort((a, b) => {
    const pa = snapshot[a]!.provider;
    const pb = snapshot[b]!.provider;
    return pa === pb ? a.localeCompare(b) : pa.localeCompare(pb);
  });

  const body = ids.map((id) => renderEntry(id, snapshot[id]!)).join('\n');

  return `/**
 * AUTO-GENERATED by scripts/sync-model-catalog.ts — DO NOT EDIT BY HAND.
 *
 * Offline model-catalog snapshot captured from https://models.dev/api.json for
 * the provider namespaces this app supports (${SUPPORTED_PROVIDERS.join(', ')}).
 * Seeded into ModelsDevService at startup via \`loadOfflineSnapshot()\`; the live
 * fetch overwrites individual entries when it lands. Pricing is USD per 1M
 * tokens; context/output limits are token counts.
 *
 * Regenerate: \`npm run sync:model-catalog\`.
 */

export interface ModelsDevSnapshotEntry {
  /** models.dev provider namespace (e.g. 'anthropic'). */
  provider: string;
  /** USD per 1M input tokens. */
  input: number;
  /** USD per 1M output tokens. */
  output: number;
  /** Total context window in tokens, when published. */
  contextWindow?: number;
  /** Max output tokens in one response, when published. */
  maxOutputTokens?: number;
}

export const MODELS_DEV_SNAPSHOT: Record<string, ModelsDevSnapshotEntry> = {
${body}
};

export const MODELS_DEV_SNAPSHOT_META = {
  source: '${MODELS_DEV_API_URL}',
  providerScope: [${SUPPORTED_PROVIDERS.map((p) => `'${p}'`).join(', ')}],
  modelCount: ${ids.length},
} as const;
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const check = process.argv.includes('--check');

  const raw = await fetchApiJson();
  if (!raw) {
    const message = 'models.dev unreachable (offline, timed out, or non-2xx).';
    if (check) {
      console.log(`sync:model-catalog — skipped: ${message}`);
      process.exit(0);
    }
    console.error(`sync:model-catalog — ${message}`);
    process.exit(1);
  }

  const snapshot = parseSnapshot(raw);
  if (!snapshot || Object.keys(snapshot).length === 0) {
    const message = 'models.dev returned no priced models for the supported providers.';
    if (check) {
      console.log(`sync:model-catalog — skipped: ${message}`);
      process.exit(0);
    }
    console.error(`sync:model-catalog — ${message}`);
    process.exit(1);
  }

  const rendered = render(snapshot);

  let current: string | null = null;
  try {
    current = readFileSync(TARGET_FILE, 'utf8');
  } catch {
    current = null;
  }

  if (current === rendered) {
    console.log(`sync:model-catalog — up to date (${Object.keys(snapshot).length} models).`);
    process.exit(0);
  }

  if (check) {
    console.error(
      'sync:model-catalog — DRIFT: the committed offline snapshot is out of date.\n' +
        'Run `npm run sync:model-catalog` to refresh.',
    );
    process.exit(1);
  }

  writeFileSync(TARGET_FILE, rendered);
  console.log(`sync:model-catalog — wrote ${Object.keys(snapshot).length} models to ${TARGET_FILE}`);
}

void main();
