/**
 * Consolidated OUTSTANDING.md export (derived artifact).
 *
 * The source of truth for outstanding items is the `loop_outstanding_items`
 * table + the Outstanding panel. This module renders a human-readable,
 * greppable/committable markdown digest on demand — never the authoritative
 * store. It groups the workspace's still-open items by loop run, then by kind.
 */

import { writeFile } from 'node:fs/promises';
import * as path from 'node:path';
import type { LoopOutstandingItem } from '../../shared/types/loop.types';

/** Default filename written at the workspace root. */
export const OUTSTANDING_EXPORT_FILENAME = 'OUTSTANDING.md';

function formatTimestamp(epochMs: number): string {
  // Stable ISO date (UTC) — avoids locale drift in a committable artifact.
  return new Date(epochMs).toISOString().slice(0, 10);
}

/**
 * Render a consolidated markdown digest of outstanding items. Items are grouped
 * by loop run (most-recent first), and within a run split into "Needs human"
 * and "Open questions". `generatedAt` is injected (not read from the clock) so
 * callers control determinism/testability.
 */
export function buildOutstandingMarkdown(
  items: LoopOutstandingItem[],
  opts: { workspaceCwd: string; generatedAt: number },
): string {
  const lines: string[] = [
    '# Outstanding',
    '',
    '> Generated by AI Orchestrator from completed loop runs. This file is a',
    '> derived digest — edits here are not synced back. Manage items in the',
    '> Outstanding panel (mark resolved / dismissed).',
    '',
    `Workspace: ${opts.workspaceCwd}`,
    `Generated: ${new Date(opts.generatedAt).toISOString()}`,
    '',
  ];

  if (items.length === 0) {
    lines.push('_No open outstanding items._', '');
    return lines.join('\n');
  }

  // Group by run, preserving the input order (caller sorts by created_at DESC).
  const byRun = new Map<string, LoopOutstandingItem[]>();
  for (const item of items) {
    const list = byRun.get(item.loopRunId) ?? [];
    list.push(item);
    byRun.set(item.loopRunId, list);
  }

  for (const [loopRunId, runItems] of byRun) {
    const first = runItems[0];
    lines.push(
      `## Loop ${loopRunId}`,
      '',
      `Status: ${first.loopStatus} · Captured: ${formatTimestamp(first.createdAt)}`,
      '',
    );
    const needsHuman = runItems.filter((i) => i.kind === 'needs-human');
    const openQuestions = runItems.filter((i) => i.kind === 'open-question');
    if (needsHuman.length > 0) {
      lines.push('### Needs human', '', ...needsHuman.map((i) => `- [ ] ${i.text}`), '');
    }
    if (openQuestions.length > 0) {
      lines.push('### Open questions', '', ...openQuestions.map((i) => `- ${i.text}`), '');
    }
  }

  return lines.join('\n');
}

/**
 * Write the consolidated digest to disk. Defaults to `<workspaceCwd>/OUTSTANDING.md`.
 * Returns the absolute path written and the item count. Throws on write failure
 * (the IPC handler surfaces it to the user).
 */
export async function exportOutstandingMarkdown(opts: {
  workspaceCwd: string;
  items: LoopOutstandingItem[];
  generatedAt: number;
  destPath?: string;
}): Promise<{ path: string; itemCount: number }> {
  const destPath = opts.destPath
    ? path.resolve(opts.destPath)
    : path.join(path.resolve(opts.workspaceCwd), OUTSTANDING_EXPORT_FILENAME);
  const markdown = buildOutstandingMarkdown(opts.items, {
    workspaceCwd: opts.workspaceCwd,
    generatedAt: opts.generatedAt,
  });
  await writeFile(destPath, markdown, 'utf8');
  return { path: destPath, itemCount: opts.items.length };
}
