import type { SettingMetadata } from './settings-metadata.types';

export const RUNTIME_SETTINGS_METADATA: SettingMetadata[] = [
  {
    key: 'outputBufferSize',
    label: 'In-Memory Buffer Size',
    description: 'Messages kept in memory per instance (older ones saved to disk)',
    type: 'number',
    category: 'memory',
    min: 100,
    max: 5000,
  },
  {
    key: 'enableDiskStorage',
    label: 'Enable Disk Storage',
    description: 'Save older output to disk to reduce memory usage',
    type: 'boolean',
    category: 'memory',
  },
  {
    key: 'maxDiskStorageMB',
    label: 'Max Disk Storage (MB)',
    description: 'Maximum disk space for output storage (0 = unlimited)',
    type: 'number',
    category: 'memory',
    min: 0,
    max: 10000,
  },
  {
    key: 'memoryWarningThresholdMB',
    label: 'Memory Warning Threshold (MB)',
    description: 'Show warning when heap usage exceeds this (0 = disabled)',
    type: 'number',
    category: 'memory',
    min: 0,
    max: 8192,
  },
  {
    key: 'autoTerminateOnMemoryPressure',
    label: 'Auto-terminate on Memory Pressure',
    description: 'Terminate idle instances when memory is critical',
    type: 'boolean',
    category: 'memory',
  },
  {
    key: 'customModelOverride',
    label: 'Custom Model Override',
    description: 'Override the default model (leave empty for CLI default)',
    type: 'string',
    category: 'advanced',
    placeholder: 'e.g., claude-3-opus-20240229',
  },
  {
    key: 'parserBufferMaxKB',
    label: 'Parser Buffer Max (KB)',
    description: 'Maximum size for NDJSON parser buffer before reset',
    type: 'number',
    category: 'advanced',
    min: 256,
    max: 10240,
  },
  {
    key: 'codememEnabled',
    label: 'Enable Codemem',
    description: 'Enable the codemem index and agent-facing code memory features',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'codememIndexingEnabled',
    label: 'Enable Codemem Indexing',
    description: 'Maintain the persistent workspace symbol and merkle index',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'codememLspWorkerEnabled',
    label: 'Enable Codemem LSP Worker',
    description: 'Start the background LSP worker used by codemem deep queries',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'commandDiagnosticsAvailable',
    label: 'Enable Command Diagnostics',
    description: 'Show command registry diagnostics in Doctor reports',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'broadRootFileThreshold',
    label: 'Broad Instruction Scan Threshold',
    description: 'Warn when project-level instruction files apply broadly above this file count',
    type: 'number',
    category: 'advanced',
    min: 0,
    max: 100000,
  },
];
