import type { SettingMetadata } from './settings-metadata.types';

export const REVIEW_NETWORK_SETTINGS_METADATA: SettingMetadata[] = [
  {
    key: 'crossModelReviewEnabled',
    label: 'Enable cross-model review',
    description: "Have a second AI model double-check an agent's work (e.g. Antigravity or Codex reviewing Claude) to catch mistakes.",
    type: 'boolean',
    category: 'review',
  },
  {
    key: 'crossModelReviewDepth',
    label: 'Review depth',
    description: 'How thorough each review is. "Structured" is a standard pass; "Tiered" automatically digs deeper for complex output.',
    type: 'select',
    category: 'review',
    options: [
      { value: 'structured', label: 'Structured (standard)' },
      { value: 'tiered', label: 'Tiered (auto-escalate for complex)' },
    ],
  },
  {
    key: 'crossModelReviewMaxReviewers',
    label: 'Reviewers per check',
    description: 'How many other models review each piece of output.',
    type: 'number',
    category: 'review',
    min: 1,
    max: 4,
  },
  {
    key: 'crossModelReviewProviders',
    label: 'Reviewer CLIs',
    description: 'Which AI CLIs may act as reviewers. Leave all unchecked to auto-pick whatever is installed.',
    type: 'multi-select',
    category: 'review',
    options: [
      { value: 'antigravity', label: 'Antigravity' },
      { value: 'codex', label: 'OpenAI Codex CLI' },
      { value: 'copilot', label: 'GitHub Copilot' },
      { value: 'claude', label: 'Claude Code' },
      { value: 'cursor', label: 'Cursor CLI' },
    ],
  },
  {
    key: 'crossModelReviewTimeout',
    label: 'Reviewer timeout (seconds)',
    description: 'How long to wait for a reviewer to respond before giving up on it.',
    type: 'number',
    category: 'review',
    min: 10,
    max: 600,
  },
  {
    key: 'crossModelReviewTypes',
    label: 'What to review',
    description: 'Which kinds of agent output get reviewed automatically.',
    type: 'multi-select',
    category: 'review',
    options: [
      { value: 'code', label: 'Code' },
      { value: 'plan', label: 'Plans' },
      { value: 'architecture', label: 'Architecture' },
    ],
  },
  {
    key: 'pingPongReviewerProvider',
    label: 'Ping-pong reviewer',
    description: 'Which CLI reviews the builder in ping-pong mode. "Auto" picks any installed model that is NOT the one doing the work.',
    type: 'select',
    category: 'review',
    options: [
      { value: 'auto', label: 'Auto (a different model)' },
      { value: 'codex', label: 'OpenAI Codex CLI' },
      { value: 'antigravity', label: 'Antigravity' },
      { value: 'copilot', label: 'GitHub Copilot' },
      { value: 'claude', label: 'Claude Code' },
      { value: 'cursor', label: 'Cursor CLI' },
    ],
  },
  {
    key: 'pingPongMaxRounds',
    label: 'Ping-pong max rounds',
    description: 'Hard cap on builder↔reviewer rounds before stopping for a human (1–20).',
    type: 'number',
    category: 'review',
    min: 1,
    max: 20,
  },
  {
    key: 'pauseFeatureEnabled',
    label: 'Enable network pausing',
    description: 'Master switch for the whole "pause when on VPN" system below. Off disables all of it.',
    type: 'boolean',
    category: 'network',
  },
  {
    key: 'pauseOnVpnEnabled',
    label: 'Pause on VPN',
    description: 'Automatically hold AI network requests while a VPN connection is active.',
    type: 'boolean',
    category: 'network',
  },
  {
    key: 'pauseVpnInterfacePattern',
    label: 'VPN interface pattern (advanced)',
    description: 'Network interfaces whose name matches this pattern are treated as a VPN. The default already covers common VPN types.',
    type: 'string',
    category: 'network',
    placeholder: '^(utun[0-9]+|ipsec[0-9]+)$',
  },
  {
    key: 'pauseTreatExistingVpnAsActive',
    label: 'Treat an already-connected VPN as active',
    description: "If a matching VPN looks connected when the app launches, assume it's active right away.",
    type: 'boolean',
    category: 'network',
  },
  {
    key: 'pauseDetectorDiagnostics',
    label: 'Log VPN detection details',
    description: 'Record extra detail about VPN detection — useful when fine-tuning the interface pattern above.',
    type: 'boolean',
    category: 'network',
  },
  {
    key: 'pauseReachabilityProbeHost',
    label: 'Reachability check host',
    description: "Optional. A host:port that's only reachable on your VPN — used as an extra signal that the VPN is up.",
    type: 'string',
    category: 'network',
    placeholder: 'host.internal:443',
  },
  {
    key: 'pauseReachabilityProbeMode',
    label: 'How to read the reachability check',
    description: 'How to interpret whether that host can be reached.',
    type: 'select',
    category: 'network',
    options: [
      { value: 'disabled', label: 'Off' },
      { value: 'reachable-means-vpn', label: 'Can reach it = VPN is on' },
      { value: 'unreachable-means-vpn', label: "Can't reach it = VPN is on" },
    ],
  },
  {
    key: 'pauseReachabilityProbeIntervalSec',
    label: 'Reachability check interval (seconds)',
    description: 'How often to run the reachability check.',
    type: 'number',
    category: 'network',
    min: 10,
    max: 600,
  },
  {
    key: 'pauseAllowPrivateRanges',
    label: 'Allow local network while paused',
    description: 'Even while paused, still allow requests to private/local addresses such as 192.168.x.x.',
    type: 'boolean',
    category: 'network',
  },
];
