import type { SettingMetadata } from './settings-metadata.types';

export const CORE_SETTINGS_METADATA: SettingMetadata[] = [
  {
    key: 'defaultYoloMode',
    label: 'YOLO Mode by Default',
    description: 'Enable YOLO mode (auto-approve all actions) for new instances',
    type: 'boolean',
    category: 'general',
  },
  {
    key: 'defaultWorkingDirectory',
    label: 'Default Working Directory',
    description: 'Starting folder for new instances (empty = home directory)',
    type: 'directory',
    category: 'general',
    placeholder: '~/Projects',
  },
  {
    key: 'defaultCli',
    label: 'Default CLI',
    description: 'Which AI CLI to use when multiple are available',
    type: 'select',
    category: 'general',
    options: [
      { value: 'auto', label: 'Auto-detect' },
      { value: 'claude', label: 'Claude Code' },
      { value: 'gemini', label: 'Gemini CLI' },
      { value: 'codex', label: 'OpenAI Codex CLI' },
      { value: 'copilot', label: 'GitHub Copilot' },
      { value: 'cursor', label: 'Cursor CLI' },
    ],
  },
  {
    key: 'defaultModel',
    label: 'Default Model',
    description: 'Model to use for new instances (passed via --model flag)',
    type: 'select',
    category: 'general',
    options: [
      { value: 'opus', label: 'Opus (latest)' },
      { value: 'sonnet', label: 'Sonnet (latest)' },
      { value: 'haiku', label: 'Haiku (latest)' },
      { value: 'gpt-5.5', label: 'GPT-5.5' },
      { value: 'gpt-5.5-mini', label: 'GPT-5.5 Mini' },
      { value: 'gpt-5.3-codex', label: 'GPT-5.3 Codex' },
      { value: 'gpt-5.3-codex-spark', label: 'GPT-5.3 Codex Spark' },
      { value: 'gpt-5.2', label: 'GPT-5.2' },
      { value: 'o3', label: 'OpenAI o3' },
      { value: 'gemini-3-pro-preview', label: 'Gemini 3.1 Pro (Preview)' },
      { value: 'gemini-3.1-pro-preview', label: 'Gemini 3.1 Pro (canonical ID — currently capacity-limited)' },
      { value: 'gemini-3-flash-preview', label: 'Gemini 3 Flash (Preview)' },
      { value: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
      { value: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
    ],
  },
  {
    key: 'theme',
    label: 'Theme',
    description: 'Application color theme',
    type: 'select',
    category: 'display',
    options: [
      { value: 'dark', label: 'Dark' },
      { value: 'light', label: 'Light' },
      { value: 'system', label: 'System' },
    ],
  },
  {
    key: 'maxChildrenPerParent',
    label: 'Max Children per Parent',
    description: 'Maximum child instances per parent (0 = unlimited)',
    type: 'number',
    category: 'orchestration',
    min: 0,
    max: 100,
  },
  {
    key: 'maxTotalInstances',
    label: 'Max Total Instances',
    description: 'Maximum total instances allowed (0 = unlimited)',
    type: 'number',
    category: 'orchestration',
    min: 0,
    max: 100,
  },
  {
    key: 'autoTerminateIdleMinutes',
    label: 'Auto-terminate Idle Instances',
    description: 'Terminate instances after N minutes of inactivity (0 = disabled)',
    type: 'number',
    category: 'orchestration',
    min: 0,
    max: 120,
  },
  {
    key: 'allowNestedOrchestration',
    label: 'Allow Nested Orchestration',
    description: 'Allow child instances to spawn their own children',
    type: 'boolean',
    category: 'orchestration',
  },
  {
    key: 'defaultMissedRunPolicy',
    label: 'Default Missed Run Policy',
    description: 'Default behavior when scheduled automation runs are missed',
    type: 'select',
    category: 'orchestration',
    options: [
      { value: 'skip', label: 'Skip' },
      { value: 'notify', label: 'Notify' },
      { value: 'runOnce', label: 'Run Once' },
    ],
  },
  {
    key: 'persistSessionContent',
    label: 'Persist Session Content',
    description: 'Save conversation and tool output to disk for session continuity',
    type: 'boolean',
    category: 'memory',
  },
  {
    key: 'fontSize',
    label: 'Font Size',
    description: 'Base font size for output display',
    type: 'number',
    category: 'display',
    min: 12,
    max: 20,
  },
  {
    key: 'displayDensity',
    label: 'Display Density',
    description: 'Spacing density for settings, shell panels, and workspace rows',
    type: 'select',
    category: 'display',
    options: [
      { value: 'comfortable', label: 'Comfortable' },
      { value: 'compact', label: 'Compact' },
    ],
  },
  {
    key: 'sidebarStyle',
    label: 'Sidebar Style',
    description: 'Sidebar width behavior for the workspace shell',
    type: 'select',
    category: 'display',
    options: [
      { value: 'standard', label: 'Standard' },
      { value: 'compact', label: 'Compact' },
    ],
  },
  {
    key: 'contextWarningThreshold',
    label: 'Context Warning Threshold',
    description: 'Show warning when context usage exceeds this percentage',
    type: 'number',
    category: 'display',
    min: 50,
    max: 100,
  },
  {
    key: 'showToolMessages',
    label: 'Show Tool Messages',
    description: 'Display tool use and tool result messages in output',
    type: 'boolean',
    category: 'display',
  },
  {
    key: 'showThinking',
    label: 'Show Thinking/Reasoning',
    description: 'Display AI thinking process in collapsible panels',
    type: 'boolean',
    category: 'display',
  },
  {
    key: 'thinkingDefaultExpanded',
    label: 'Expand Thinking by Default',
    description: 'Show thinking panels expanded instead of collapsed',
    type: 'boolean',
    category: 'display',
  },
  {
    key: 'maxRecentDirectories',
    label: 'Recent Directories Limit',
    description: 'Maximum number of recently opened directories to remember',
    type: 'number',
    category: 'display',
    min: 5,
    max: 500,
  },
];
