import type { SettingMetadata } from './settings-metadata.types';

export const CORE_SETTINGS_METADATA: SettingMetadata[] = [
  {
    key: 'defaultYoloMode',
    label: 'Auto-approve actions by default',
    description: 'New instances skip the approval prompts and act on their own. Faster, but riskier — only turn this on for trusted, sandboxed work.',
    type: 'boolean',
    category: 'general',
  },
  {
    key: 'defaultWorkingDirectory',
    label: 'Default working directory',
    description: 'Starting folder for new instances. Leave empty to use your home directory.',
    type: 'directory',
    category: 'general',
    placeholder: '~/Projects',
  },
  {
    key: 'defaultCli',
    label: 'Default AI CLI',
    description: 'Which AI command-line tool a new instance uses. "Auto-detect" picks the first one you have installed.',
    type: 'select',
    category: 'general',
    options: [
      { value: 'auto', label: 'Auto-detect' },
      { value: 'claude', label: 'Claude Code' },
      { value: 'antigravity', label: 'Antigravity' },
      { value: 'codex', label: 'OpenAI Codex CLI' },
      { value: 'copilot', label: 'GitHub Copilot' },
      { value: 'cursor', label: 'Cursor CLI' },
    ],
  },
  {
    key: 'defaultModel',
    label: 'Default model',
    description: 'Which model new instances start with, when the chosen CLI lets you pick one.',
    type: 'select',
    category: 'general',
    options: [
      { value: 'opus', label: 'Opus (latest)' },
      { value: 'sonnet', label: 'Sonnet (latest)' },
      { value: 'haiku', label: 'Haiku (latest)' },
      { value: 'gpt-5.5', label: 'GPT-5.5' },
      { value: 'gpt-5.5-mini', label: 'GPT-5.5 Mini' },
      { value: 'gpt-5.3-codex', label: 'GPT-5.3 Codex' },
      { value: 'gpt-5.3-codex-spark', label: 'GPT-5.3 Codex Spark' },
      { value: 'gpt-5.2', label: 'GPT-5.2' },
      { value: 'o3', label: 'OpenAI o3' },
      { value: 'gemini-3-pro-preview', label: 'Gemini 3.1 Pro (Preview)' },
      { value: 'gemini-3.1-pro-preview', label: 'Gemini 3.1 Pro (canonical ID — currently capacity-limited)' },
      { value: 'gemini-3-flash-preview', label: 'Gemini 3 Flash (Preview)' },
      { value: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
      { value: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
    ],
  },
  {
    key: 'theme',
    label: 'Theme',
    description: 'Light, dark, or follow your operating system.',
    type: 'select',
    category: 'display',
    options: [
      { value: 'dark', label: 'Dark' },
      { value: 'light', label: 'Light' },
      { value: 'system', label: 'System' },
    ],
  },
  {
    key: 'outputStyle',
    label: 'Output style',
    description: 'Adds a communication-style directive to new agents. Default makes no change; Explanatory adds teaching asides, Learning hands you small pieces to do, Concise trims prose.',
    type: 'select',
    category: 'display',
    options: [
      { value: 'default', label: 'Default' },
      { value: 'explanatory', label: 'Explanatory' },
      { value: 'learning', label: 'Learning' },
      { value: 'concise', label: 'Concise' },
    ],
  },
  {
    key: 'maxChildrenPerParent',
    label: 'Maximum sub-agents per agent',
    description: 'How many helper agents one agent may spawn to split up a task. 0 means no limit.',
    type: 'number',
    category: 'orchestration',
    min: 0,
    max: 100,
  },
  {
    key: 'maxTotalInstances',
    label: 'Maximum agents running at once',
    description: 'Hard ceiling on how many agents can run at the same time across the whole app. 0 means no limit.',
    type: 'number',
    category: 'orchestration',
    min: 0,
    max: 100,
  },
  {
    key: 'autoTerminateIdleMinutes',
    label: 'Close idle agents after',
    description: 'Automatically shut down an agent after this many minutes with no activity, to free up resources. 0 keeps them running indefinitely.',
    type: 'number',
    category: 'orchestration',
    min: 0,
    max: 120,
  },
  {
    key: 'allowNestedOrchestration',
    label: 'Let sub-agents spawn their own sub-agents',
    description: 'Allow helper agents to start their own helpers (deeper delegation). Off keeps the hierarchy one level deep.',
    type: 'boolean',
    category: 'orchestration',
  },
  {
    key: 'maxSpawnDepth',
    label: 'Maximum delegation depth',
    description: 'How many levels deep helper agents may nest (a helper of a helper is level 2). Caps runaway "agent-spawning-agent" chains, including agents run on remote nodes. 0 means no limit.',
    type: 'number',
    category: 'orchestration',
    min: 0,
    max: 10,
  },
  {
    key: 'defaultMissedRunPolicy',
    label: 'When a scheduled run is missed',
    description: 'What to do if a scheduled task was due while the app was closed or busy.',
    type: 'select',
    category: 'orchestration',
    options: [
      { value: 'skip', label: 'Skip it' },
      { value: 'notify', label: 'Just notify me' },
      { value: 'runOnce', label: 'Run it once on next launch' },
    ],
  },
  {
    key: 'reactionsEnabled',
    label: 'Event-driven reactions (global master switch)',
    description: 'On by default. The engine is willing to react, but only instances you individually arm will auto-react to CI failures, review requests, and merge conflicts (by sending a fix prompt). Turning this off is a global kill switch. Arming is still per-instance and off by default, so default-on never auto-prompts an instance you did not arm.',
    type: 'boolean',
    category: 'orchestration',
  },
  {
    key: 'reactionsPollIntervalMs',
    label: 'Reaction poll interval (ms)',
    description: 'How often the reaction engine checks PR/CI state for armed instances. Only relevant when reactions are enabled. Default: 60 000 (1 min).',
    type: 'number',
    category: 'orchestration',
    min: 10_000,
    max: 300_000,
  },
  {
    key: 'persistSessionContent',
    label: 'Save conversation history to disk',
    description: "Keep each session's messages and tool output on disk so you can reopen and continue it later.",
    type: 'boolean',
    category: 'memory',
  },
  {
    key: 'fontSize',
    label: 'Output font size',
    description: 'Text size for agent responses and transcript output.',
    type: 'number',
    category: 'display',
    min: 12,
    max: 20,
  },
  {
    key: 'displayDensity',
    label: 'Display density',
    description: 'How tightly packed the interface is. "Compact" fits more on screen; "Comfortable" adds breathing room.',
    type: 'select',
    category: 'display',
    options: [
      { value: 'comfortable', label: 'Comfortable' },
      { value: 'compact', label: 'Compact' },
    ],
  },
  {
    key: 'sidebarStyle',
    label: 'Sidebar style',
    description: 'How wide the left sidebar is in the main workspace.',
    type: 'select',
    category: 'display',
    options: [
      { value: 'standard', label: 'Standard' },
      { value: 'compact', label: 'Compact' },
    ],
  },
  {
    key: 'contextWarningThreshold',
    label: 'Context-full warning at',
    description: "Show a warning once a session has used this percentage of the model's context window (how much it can keep in mind at once).",
    type: 'number',
    category: 'display',
    min: 50,
    max: 100,
  },
  {
    key: 'showToolMessages',
    label: 'Show tool activity',
    description: 'Show tool calls and their results in the transcript.',
    type: 'boolean',
    category: 'display',
  },
  {
    key: 'showThinking',
    label: 'Show reasoning panels',
    description: "Show the AI's reasoning in collapsible panels in the transcript.",
    type: 'boolean',
    category: 'display',
  },
  {
    key: 'showCost',
    label: 'Show cost estimates',
    description: 'Show running USD cost estimates per instance and across all instances. Turn off to hide spend in managed setups.',
    type: 'boolean',
    category: 'display',
  },
  {
    key: 'thinkingDefaultExpanded',
    label: 'Expand reasoning by default',
    description: 'Open reasoning panels automatically instead of keeping them collapsed.',
    type: 'boolean',
    category: 'display',
  },
  {
    key: 'maxRecentDirectories',
    label: 'Recent folders to remember',
    description: 'How many recently opened folders to keep in your workspace history.',
    type: 'number',
    category: 'display',
    min: 5,
    max: 500,
  },
];
