import type { SettingMetadata } from './settings-metadata.types';
import { PROVIDER_MODEL_LIST } from './provider.types';

const DEFAULT_MODEL_SETTING_PROVIDERS = ['claude', 'codex', 'gemini'] as const;

function buildDefaultModelOptions(): { value: string; label: string }[] {
  return DEFAULT_MODEL_SETTING_PROVIDERS.flatMap((provider) =>
    (PROVIDER_MODEL_LIST[provider] ?? []).map((model) => ({
      value: model.id,
      label: model.name,
    })),
  );
}

export const CORE_SETTINGS_METADATA: SettingMetadata[] = [
  {
    key: 'defaultYoloMode',
    label: 'Auto-approve actions by default',
    description: 'New instances skip the approval prompts and act on their own. Faster, but riskier — only turn this on for trusted, sandboxed work.',
    type: 'boolean',
    category: 'general',
  },
  {
    key: 'defaultFastMode',
    label: 'Fast mode by default',
    description: 'New Claude/Codex instances start in fast mode (faster output via Opus fast mode / Codex priority tier). Requires a paid plan; instances auto-revert if it is unavailable.',
    type: 'boolean',
    category: 'general',
  },
  {
    key: 'defaultWorkingDirectory',
    label: 'Default working directory',
    description: 'Starting folder for new instances. Leave empty to use your home directory.',
    type: 'directory',
    category: 'general',
    placeholder: '~/Projects',
  },
  {
    key: 'defaultCli',
    label: 'Default AI CLI',
    description: 'Which AI command-line tool a new instance uses. "Auto-detect" picks the first one you have installed.',
    type: 'select',
    category: 'general',
    options: [
      { value: 'auto', label: 'Auto-detect' },
      { value: 'claude', label: 'Claude Code' },
      { value: 'antigravity', label: 'Antigravity' },
      { value: 'codex', label: 'OpenAI Codex CLI' },
      { value: 'copilot', label: 'GitHub Copilot' },
      { value: 'cursor', label: 'Cursor CLI' },
    ],
  },
  {
    key: 'defaultModel',
    label: 'Default model',
    description: 'Which model new instances start with, when the chosen CLI lets you pick one.',
    type: 'select',
    category: 'general',
    options: buildDefaultModelOptions(),
  },
  {
    key: 'customModelsByProvider',
    label: 'Custom models by provider',
    description: 'Provider-specific model ids added by the user. Edit these from Settings → Models so each provider list can validate duplicates.',
    type: 'json',
    category: 'advanced',
    hidden: true,
  },
  {
    key: 'modelCatalogRemoteOverrideUrl',
    label: 'Remote model catalog override',
    description: 'Optional HTTP(S) JSON catalog URL. Requests are still filtered by the app network policy; leave empty to disable.',
    type: 'string',
    category: 'advanced',
    placeholder: 'https://catalog.example.com/models-override.json',
  },
  {
    key: 'theme',
    label: 'Theme',
    description: 'Light, dark, or follow your operating system.',
    type: 'select',
    category: 'display',
    options: [
      { value: 'dark', label: 'Dark' },
      { value: 'light', label: 'Light' },
      { value: 'system', label: 'System' },
    ],
  },
  {
    key: 'outputStyle',
    label: 'Output style',
    description: 'Adds a communication-style directive to new agents. Default makes no change; Explanatory adds teaching asides, Learning hands you small pieces to do, Concise trims prose.',
    type: 'select',
    category: 'display',
    options: [
      { value: 'default', label: 'Default' },
      { value: 'explanatory', label: 'Explanatory' },
      { value: 'learning', label: 'Learning' },
      { value: 'concise', label: 'Concise' },
    ],
  },
  {
    key: 'maxChildrenPerParent',
    label: 'Maximum sub-agents per agent',
    description: 'How many helper agents one agent may spawn to split up a task. 0 means no limit.',
    type: 'number',
    category: 'orchestration',
    min: 0,
    max: 100,
  },
  {
    key: 'maxTotalInstances',
    label: 'Maximum agents running at once',
    description: 'Hard ceiling on how many agents can run at the same time across the whole app. 0 means no limit.',
    type: 'number',
    category: 'orchestration',
    min: 0,
    max: 100,
  },
  {
    key: 'autoTerminateIdleMinutes',
    label: 'Close idle agents after',
    description: 'Automatically shut down an agent after this many minutes with no activity, to free up resources. 0 keeps them running indefinitely.',
    type: 'number',
    category: 'orchestration',
    min: 0,
    max: 120,
  },
  {
    key: 'allowNestedOrchestration',
    label: 'Let sub-agents spawn their own sub-agents',
    description: 'Allow helper agents to start their own helpers (deeper delegation). Off keeps the hierarchy one level deep.',
    type: 'boolean',
    category: 'orchestration',
  },
  {
    key: 'maxSpawnDepth',
    label: 'Maximum delegation depth',
    description: 'How many levels deep helper agents may nest (a helper of a helper is level 2). Caps runaway "agent-spawning-agent" chains, including agents run on remote nodes. 0 means no limit.',
    type: 'number',
    category: 'orchestration',
    min: 0,
    max: 10,
  },
  {
    key: 'defaultMissedRunPolicy',
    label: 'When a scheduled run is missed',
    description: 'What to do if a scheduled task was due while the app was closed or busy.',
    type: 'select',
    category: 'orchestration',
    options: [
      { value: 'skip', label: 'Skip it' },
      { value: 'notify', label: 'Just notify me' },
      { value: 'runOnce', label: 'Run it once on next launch' },
    ],
  },
  {
    key: 'instanceProviderLimitResumeEnabled',
    label: 'Auto-resume sessions after a provider limit',
    description: 'When a regular chat session stops on a provider rate/session limit, park it and automatically re-send your message once the quota window resets (loops already do this). Off by default: unattended resumes can spend quota while you are away.',
    type: 'boolean',
    category: 'orchestration',
  },
  {
    key: 'reactionsEnabled',
    label: 'Event-driven reactions (global master switch)',
    description: 'On by default. The engine is willing to react, but only instances you individually arm will auto-react to CI failures, review requests, and merge conflicts (by sending a fix prompt). Turning this off is a global kill switch. Arming is still per-instance and off by default, so default-on never auto-prompts an instance you did not arm.',
    type: 'boolean',
    category: 'orchestration',
  },
  {
    key: 'reactionsPollIntervalMs',
    label: 'Reaction poll interval (ms)',
    description: 'How often the reaction engine checks PR/CI state for armed instances. Only relevant when reactions are enabled. Default: 60 000 (1 min).',
    type: 'number',
    category: 'orchestration',
    min: 10_000,
    max: 300_000,
  },
  {
    key: 'persistSessionContent',
    label: 'Save conversation history to disk',
    description: "Keep each session's messages and tool output on disk so you can reopen and continue it later.",
    type: 'boolean',
    category: 'memory',
  },
  {
    key: 'fontSize',
    label: 'Output font size',
    description: 'Text size for agent responses and transcript output.',
    type: 'number',
    category: 'display',
    min: 12,
    max: 20,
  },
  {
    key: 'displayDensity',
    label: 'Display density',
    description: 'How tightly packed the interface is. "Compact" fits more on screen; "Comfortable" adds breathing room.',
    type: 'select',
    category: 'display',
    options: [
      { value: 'comfortable', label: 'Comfortable' },
      { value: 'compact', label: 'Compact' },
    ],
  },
  {
    key: 'sidebarStyle',
    label: 'Sidebar style',
    description: 'How wide the left sidebar is in the main workspace.',
    type: 'select',
    category: 'display',
    options: [
      { value: 'standard', label: 'Standard' },
      { value: 'compact', label: 'Compact' },
    ],
  },
  {
    key: 'contextWarningThreshold',
    label: 'Context-full warning at',
    description: "Show a warning once a session has used this percentage of the model's context window (how much it can keep in mind at once).",
    type: 'number',
    category: 'display',
    min: 50,
    max: 100,
  },
  {
    key: 'showToolMessages',
    label: 'Show tool activity',
    description: 'Show tool calls and their results in the transcript.',
    type: 'boolean',
    category: 'display',
  },
  {
    key: 'showThinking',
    label: 'Show reasoning panels',
    description: "Show the AI's reasoning in collapsible panels in the transcript.",
    type: 'boolean',
    category: 'display',
  },
  {
    key: 'showCost',
    label: 'Show cost estimates',
    description: 'Show running USD cost estimates per instance and across all instances. Turn off to hide spend in managed setups.',
    type: 'boolean',
    category: 'display',
  },
  {
    key: 'thinkingDefaultExpanded',
    label: 'Expand reasoning by default',
    description: 'Open reasoning panels automatically instead of keeping them collapsed.',
    type: 'boolean',
    category: 'display',
  },
  {
    key: 'maxRecentDirectories',
    label: 'Recent folders to remember',
    description: 'How many recently opened folders to keep in your workspace history.',
    type: 'number',
    category: 'display',
    min: 5,
    max: 500,
  },
];
