import type { SettingMetadata } from './settings-metadata.types';

export const INTEGRATION_SETTINGS_METADATA: SettingMetadata[] = [
  {
    key: 'graphClientId',
    label: 'Microsoft Graph application ID',
    description: 'Public client application ID used for delegated Microsoft calendar access. The current registration is single-tenant; no client secret is stored.',
    type: 'string',
    category: 'mcp',
  },
  {
    key: 'graphAuthority',
    label: 'Microsoft Graph authority',
    description: 'Microsoft identity authority for delegated calendar access. The current single-tenant app requires its tenant-specific authority; use /common only after enabling multitenant and personal accounts in Entra.',
    type: 'string',
    category: 'mcp',
  },
  {
    key: 'graphScopesJson',
    label: 'Microsoft Graph scopes',
    description: 'JSON array of delegated permissions requested during Microsoft calendar consent.',
    type: 'json',
    category: 'mcp',
  },
  {
    key: 'graphAgentWritableAccountsJson',
    label: 'Agent-writable Microsoft calendars',
    description: 'JSON array of connected account emails agents may create, update, or delete events on. Other connected accounts remain read-only.',
    type: 'json',
    category: 'mcp',
  },
  {
    key: 'mcpCleanupBackupsOnQuit',
    label: 'Delete MCP config backups on quit',
    description: 'When the app quits, remove the ".orc.bak" safety copies it makes before editing a provider\'s MCP config file.',
    type: 'boolean',
    category: 'mcp',
  },
  {
    key: 'mcpDisableProviderBackups',
    label: "Don't back up MCP configs before editing",
    description: "Skip making a safety copy before editing a provider's MCP config. Not recommended — backups let you recover if an edit goes wrong.",
    type: 'boolean',
    category: 'mcp',
  },
  {
    key: 'mcpAllowWorldWritableParent',
    label: 'Allow MCP configs in world-writable folders',
    description: 'Allow editing MCP configs even when their folder can be written by any user on the machine. Normally blocked, because it is a security risk.',
    type: 'boolean',
    category: 'mcp',
  },
  {
    key: 'computerUseEnabled',
    label: 'Enable Computer Use',
    description: 'Expose the Harness-owned computer-use MCP server to local agents. Keep this off unless you are ready to approve app-scoped desktop access.',
    type: 'boolean',
    category: 'mcp',
  },
  {
    key: 'computerUseAllowedAppsJson',
    label: 'Computer Use allowed apps',
    description: 'JSON array of app ids, bundle ids, executable paths, or display names allowed for observe-only Computer Use.',
    type: 'json',
    category: 'mcp',
  },
  {
    key: 'computerUseDeniedAppsJson',
    label: 'Computer Use denied apps',
    description: 'JSON array of app ids, bundle ids, executable paths, or display names that Computer Use must never inspect or control.',
    type: 'json',
    category: 'mcp',
  },
  {
    key: 'computerUseRequireApprovalForInput',
    label: 'Require approval for Computer Use input',
    description: 'Require explicit approval before any desktop input action can run. Input tools stay unavailable until the policy and token checks are active.',
    type: 'boolean',
    category: 'mcp',
  },
  {
    key: 'computerUseStoreScreenshotsForEscalations',
    label: 'Store Computer Use escalation screenshots',
    description: 'Allow Computer Use to retain screenshot artifacts only when an escalation is raised. Screenshot bytes are never written to the audit log.',
    type: 'boolean',
    category: 'mcp',
  },
  {
    key: 'rtkEnabled',
    label: 'Compress command output to save tokens',
    description: 'Shrink the shell-command output sent to the model by 60–90% using the bundled "RTK" tool, so you spend fewer tokens. Restart the app to apply this to running instances.',
    type: 'boolean',
    category: 'rtk',
  },
  {
    key: 'rtkBundledOnly',
    label: 'Only use the built-in RTK',
    description: 'Always use the RTK tool shipped inside this app, never one installed elsewhere on your system. Keeps behavior consistent across machines.',
    type: 'boolean',
    category: 'rtk',
  },
  {
    key: 'notifyOnAgentCompletion',
    label: 'Notify when an agent finishes',
    description: 'Show a desktop notification when an agent goes from busy to idle (only when this window is not focused).',
    type: 'boolean',
    category: 'general',
  },
  {
    key: 'channelToolHeartbeat',
    label: 'Chat bot: heartbeat on long turns',
    description: 'Post an occasional throttled "still working…" line to Discord/WhatsApp while an agent runs a long, silent turn. Off keeps channels quiet.',
    type: 'boolean',
    category: 'general',
  },
  {
    key: 'notificationCooldownSeconds',
    label: 'Notification cooldown',
    description: 'Minimum seconds between desktop notifications of the same kind. Suppressed events still appear in the in-app notification center.',
    type: 'number',
    category: 'general',
    min: 0,
    max: 3600,
  },
  {
    key: 'notificationQuietHoursEnabled',
    label: 'Quiet hours',
    description: 'During quiet hours, normal notifications stay in the in-app center instead of showing on the desktop. Critical alerts still appear.',
    type: 'boolean',
    category: 'general',
  },
  {
    key: 'notificationQuietHoursStartHour',
    label: 'Quiet hours start',
    description: 'Local hour when quiet hours begin (0–23).',
    type: 'number',
    category: 'general',
    min: 0,
    max: 23,
  },
  {
    key: 'notificationQuietHoursEndHour',
    label: 'Quiet hours end',
    description: 'Local hour when quiet hours end (0–23).',
    type: 'number',
    category: 'general',
    min: 0,
    max: 23,
  },
  {
    key: 'cliUpdatePolicy',
    label: 'CLI provider updates',
    description: 'How to handle newer versions of the AI CLIs this app wraps (Claude, Codex, Gemini, Copilot). "Notify" shows a one-click update button; "Auto-apply" installs safe updates for you when no instances are running; "Off" hides update checks.',
    type: 'select',
    category: 'general',
    options: [
      { value: 'notify', label: 'Notify me (one-click update)' },
      { value: 'auto', label: 'Auto-apply safe updates' },
      { value: 'off', label: 'Off' },
    ],
  },
];
