import type { SettingMetadata } from './settings-metadata.types';

export const REVIEW_NETWORK_SETTINGS_METADATA: SettingMetadata[] = [
  {
    key: 'crossModelReviewEnabled',
    label: 'Enable Cross-Model Review',
    description: 'Automatically verify AI output using secondary models (Gemini, Codex, etc.)',
    type: 'boolean',
    category: 'review',
  },
  {
    key: 'crossModelReviewDepth',
    label: 'Review Depth',
    description: 'Level of verification detail (structured = standard, tiered = deep for complex output)',
    type: 'select',
    category: 'review',
    options: [
      { value: 'structured', label: 'Structured (standard)' },
      { value: 'tiered', label: 'Tiered (auto-escalate for complex)' },
    ],
  },
  {
    key: 'crossModelReviewMaxReviewers',
    label: 'Max Reviewers',
    description: 'Number of secondary models to use for each review',
    type: 'number',
    category: 'review',
    min: 1,
    max: 4,
  },
  {
    key: 'crossModelReviewProviders',
    label: 'Preferred Review Providers',
    description: 'Which CLIs to use for reviews (empty = auto-detect available)',
    type: 'multi-select',
    category: 'review',
    options: [
      { value: 'gemini', label: 'Gemini CLI' },
      { value: 'codex', label: 'OpenAI Codex CLI' },
      { value: 'copilot', label: 'GitHub Copilot' },
      { value: 'claude', label: 'Claude Code' },
      { value: 'cursor', label: 'Cursor CLI' },
    ],
  },
  {
    key: 'crossModelReviewTimeout',
    label: 'Review Timeout (seconds)',
    description: 'Maximum time to wait for each reviewer response',
    type: 'number',
    category: 'review',
    min: 10,
    max: 120,
  },
  {
    key: 'crossModelReviewTypes',
    label: 'Review Triggers',
    description: 'Which output types trigger automatic review',
    type: 'multi-select',
    category: 'review',
    options: [
      { value: 'code', label: 'Code' },
      { value: 'plan', label: 'Plans' },
      { value: 'architecture', label: 'Architecture' },
    ],
  },
  {
    key: 'pauseFeatureEnabled',
    label: 'Enable VPN pause feature',
    description: 'Master switch for VPN pause, detector, network gate, and queue persistence.',
    type: 'boolean',
    category: 'network',
  },
  {
    key: 'pauseOnVpnEnabled',
    label: 'Pause on VPN',
    description: 'Automatically pause AI traffic when a VPN is detected.',
    type: 'boolean',
    category: 'network',
  },
  {
    key: 'pauseVpnInterfacePattern',
    label: 'Interface pattern',
    description: 'Network interface names matching this regex are treated as VPN.',
    type: 'string',
    category: 'network',
    placeholder: '^(utun[0-9]+|ipsec[0-9]+)$',
  },
  {
    key: 'pauseTreatExistingVpnAsActive',
    label: 'Treat existing VPN as active',
    description: 'If a calibrated matching interface is present at launch, treat the VPN as already up.',
    type: 'boolean',
    category: 'network',
  },
  {
    key: 'pauseDetectorDiagnostics',
    label: 'Verbose detection logging',
    description: 'Record detector ticks for VPN pattern calibration.',
    type: 'boolean',
    category: 'network',
  },
  {
    key: 'pauseReachabilityProbeHost',
    label: 'Reachability probe host',
    description: 'Optional host:port for a VPN-only reachability check.',
    type: 'string',
    category: 'network',
    placeholder: 'host.internal:443',
  },
  {
    key: 'pauseReachabilityProbeMode',
    label: 'Probe mode',
    description: 'How to interpret reachability probe results.',
    type: 'select',
    category: 'network',
    options: [
      { value: 'disabled', label: 'Disabled' },
      { value: 'reachable-means-vpn', label: 'Reachable means VPN' },
      { value: 'unreachable-means-vpn', label: 'Unreachable means VPN' },
    ],
  },
  {
    key: 'pauseReachabilityProbeIntervalSec',
    label: 'Probe interval',
    description: 'How often to run the reachability probe.',
    type: 'number',
    category: 'network',
    min: 10,
    max: 600,
  },
  {
    key: 'pauseAllowPrivateRanges',
    label: 'Allow private ranges during pause',
    description: 'Permit RFC 1918 private network hosts while paused.',
    type: 'boolean',
    category: 'network',
  },
];
