import type { SettingMetadata } from './settings-metadata.types';

export const RUNTIME_SETTINGS_METADATA: SettingMetadata[] = [
  {
    key: 'outputBufferSize',
    label: 'Messages kept in memory per agent',
    description: 'How many recent messages stay in memory for each agent. Older ones move to disk (when disk storage is on).',
    type: 'number',
    category: 'memory',
    min: 100,
    max: 5000,
  },
  {
    key: 'enableDiskStorage',
    label: 'Save older output to disk',
    description: 'Move older transcript output out of memory and onto disk, so the app uses less RAM.',
    type: 'boolean',
    category: 'memory',
  },
  {
    key: 'maxDiskStorageMB',
    label: 'Disk storage limit (MB)',
    description: 'Most disk space to use for saved output, in megabytes. 0 means no limit.',
    type: 'number',
    category: 'memory',
    min: 0,
    max: 10000,
  },
  {
    key: 'memoryWarningThresholdMB',
    label: 'Memory warning threshold (MB)',
    description: "Warn when the app's memory use climbs above this many megabytes. 0 turns the warning off.",
    type: 'number',
    category: 'memory',
    min: 0,
    max: 8192,
  },
  {
    key: 'autoTerminateOnMemoryPressure',
    label: 'Close idle agents when memory runs low',
    description: 'If the app is close to running out of memory, automatically shut down idle agents to recover.',
    type: 'boolean',
    category: 'memory',
  },
  {
    key: 'cumulativeTokenCompactionTrigger',
    label: 'Compact after token spend',
    description: 'Automatically compact an agent once it has spent this many tokens since its last compaction, regardless of how full its context window is — a cost cap for long sessions. 0 turns it off.',
    type: 'number',
    category: 'memory',
    min: 0,
    max: 10_000_000,
  },
  {
    key: 'customModelOverride',
    label: 'Custom model override',
    description: 'Force a specific model name for every new instance, ignoring the Default model setting. Leave empty to use the CLI\'s own default.',
    type: 'string',
    category: 'advanced',
    placeholder: 'e.g., claude-3-opus-20240229',
  },
  {
    key: 'parserBufferMaxKB',
    label: 'Output parser buffer limit (KB)',
    description: 'Largest chunk of streamed CLI output the parser holds before resetting. Raise it only if very long output lines get cut off.',
    type: 'number',
    category: 'advanced',
    min: 256,
    max: 10240,
  },
  {
    key: 'chromeDevtoolsAttachEnabled',
    label: 'Attach chrome-devtools to a managed browser profile',
    description: 'Give agents a chrome-devtools MCP server wired to a managed browser profile, so they can drive the same authenticated browser they open with the browser tools. When this is on, Harness owns the single "chrome-devtools" server — do not also add a separate chrome-devtools MCP server, or their tools will collide.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'chromeDevtoolsAttachProfileId',
    label: 'chrome-devtools managed profile',
    description: 'The managed browser profile chrome-devtools attaches to. Pick one of your managed profiles from the Browser screen. Only used when the attach toggle above is on.',
    type: 'select',
    category: 'advanced',
  },
  {
    key: 'browserVaultMasterPasswordFile',
    label: 'Credential vault master-password file',
    description: 'Path to a local file holding the Bitwarden master password used to unlock the browser credential vault. Only the path is stored; the password is read at unlock time, kept in memory only, and never logged or shown. Leave empty to disable unlock.',
    type: 'string',
    category: 'advanced',
    placeholder: 'e.g., /Users/you/secure/bitwarden-master.txt',
  },
  {
    key: 'browserVaultAutoUnlock',
    label: 'Auto-unlock the credential vault at startup',
    description: 'Unlock the browser credential vault automatically when the app starts, reading the master-password file above. Turn this on for hands-free unattended runs so you never click "Unlock vault". Needs a readable master-password file to be set. Set only from here or via the AIO_BW_MASTER_PASSWORD_FILE launch env var — not changeable by agents.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'browserAllowSharedTabCredentialFill',
    label: 'Allow autonomous sign-in on your shared browser tabs',
    description: 'Let the agent fill saved credentials (and login/registration forms) on your OWN shared Chrome tabs, not just its managed profiles — for portals where your registered accounts live in your real browser. Only origins you have granted a standing credential authorization can be filled; the password is typed straight into the page and never shown to the agent or logged. Off by default. Set only from here or via the privileged operator CLI — not changeable by agents.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'sessionFailoverProviders',
    label: 'Fallback providers for failed sessions',
    description: 'When a chat session cannot recover on its current provider (auth, quota, or provider outages), automatically move the conversation to the next provider in this list instead of leaving it dead. Empty = off. Setting this is your consent to send the conversation to those providers.',
    type: 'multi-select',
    category: 'advanced',
  },
  {
    key: 'sessionFailoverMaxSwitches',
    label: 'Max automatic provider switches per session',
    description: 'How many times a single session may automatically fail over before it stops trying and surfaces the error.',
    type: 'number',
    category: 'advanced',
    min: 1,
    max: 6,
  },
  {
    key: 'instructionTrustGate',
    label: 'Project instruction-file trust gate',
    description: 'Guard against prompt injection via repo instruction files (CLAUDE.md, AGENTS.md, …). "warn": load them but flag unapproved/changed files. "enforce": skip files you have not approved (or that changed since approval, or carry critical scanner findings). "off": load everything as before. Your global ~/.claude files are always exempt.',
    type: 'select',
    options: [
      { value: 'off', label: 'Off — load everything (pre-gate behavior)' },
      { value: 'warn', label: 'Warn — load, but flag unapproved/changed files' },
      { value: 'enforce', label: 'Enforce — skip unapproved/changed/flagged files' },
    ],
    category: 'advanced',
  },
  {
    key: 'sessionFailoverOfferAfterMinutes',
    label: 'Offer a provider switch after parked (minutes)',
    description: 'When a session is parked on a provider limit and the resume is further away than this, offer switching to a fallback provider (needs the fallback list above).',
    type: 'number',
    category: 'advanced',
    min: 1,
    max: 720,
  },
  {
    key: 'sessionHandoffStateEnabled',
    label: 'Maintained handoff context for swaps and restores',
    description: 'Keep a rolling summary of each session as it runs, and hand that to the new session when you switch provider/model or restore from history — instead of rebuilding a transcript excerpt at switch time. Off by default while the feature is validated.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'memoryInstructionGate',
    label: 'Gate agent-written memories from instructions',
    description: 'Keep memories the agent wrote itself out of system-prompt-tier content — they can still appear in clearly-labelled advisory blocks, but are never treated as authoritative instructions. Recommended on.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'claudeFallbackModel',
    label: 'Claude fallback model on overload',
    description: 'When Claude reports the primary model as overloaded, automatically retry the request with this model instead of failing the turn. Leave empty to disable. Applies at the next session spawn.',
    type: 'string',
    category: 'advanced',
  },
  {
    key: 'claudeSubprocessEnvScrub',
    label: 'Scrub environment from Claude subprocesses',
    description: 'Sets CLAUDE_CODE_SUBPROCESS_ENV_SCRUB=1 so commands the Claude CLI runs do not inherit sensitive environment variables. Off by default: the scrub may also strip the orchestrator variables that power the approval hook and RTK — enable only after verifying those still work.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'browserMcpToolDeferral',
    label: 'Load browser tools on demand',
    description: 'Give new agent sessions a small core set of browser tools plus a search tool that loads the rest on demand, instead of injecting all ~39 tool schemas upfront. Cuts per-session context cost; agents discover extra tools with browser.tool_search. Applies at the next session spawn.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'codememEnabled',
    label: 'Enable code memory',
    description: 'Let agents look up symbols and structure from a lightweight index of your code ("codemem"). Turning this off disables all the code-memory options below.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'codememIndexingEnabled',
    label: 'Keep the code index up to date',
    description: "Continuously index your project's symbols so code lookups stay accurate as files change.",
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'codememLspWorkerEnabled',
    label: 'Enable deep code queries',
    description: 'Run a background language server so agents can answer deeper questions like "who calls this?" or "where is this defined?". Uses more CPU and memory.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'codememPrewarmEnabled',
    label: 'Warm up the code index when a folder opens',
    description:
      'Start building the code index the moment you open a folder, instead of waiting for the first agent. Makes the first code lookup faster.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'codememPrewarmMaxConcurrent',
    label: 'Index warm-ups at once',
    description: 'How many folders can build their code index at the same time. Higher is faster but heavier on your machine.',
    type: 'number',
    category: 'advanced',
    min: 1,
    max: 8,
  },
  {
    key: 'codememPrewarmDebounceMs',
    label: 'Index warm-up delay (ms)',
    description:
      "Wait this long after a folder opens before warming its index, so clicking quickly through folders doesn't kick off many warm-ups at once.",
    type: 'number',
    category: 'advanced',
    min: 0,
    max: 60000,
  },
  {
    key: 'codememPrewarmStartupHint',
    label: 'Warm up your last folder at launch',
    description:
      'When the app starts, pre-build the code index for the folder you used most recently.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'commandDiagnosticsAvailable',
    label: 'Include command diagnostics in Doctor',
    description: 'Add slash-command and command-registry checks to the Doctor diagnostics report.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'broadRootFileThreshold',
    label: 'Broad instruction-file warning',
    description: 'Warn when a project instruction file (e.g. AGENTS.md) would apply to more than this many files — a sign its scope is too broad.',
    type: 'number',
    category: 'advanced',
    min: 0,
    max: 100000,
  },
  {
    key: 'codebaseAutoIndexEnabled',
    label: 'Auto-run the legacy codebase index',
    description:
      "Automatically run the older, heavier full-text + embedding search index when a folder opens. Most people should leave this off — it's mainly for debugging the legacy search path.",
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'quotaPacingWarningEnabled',
    label: 'Warn when quota is being consumed too quickly',
    description: 'Shows an early warning when a known quota window is mostly used before most of its time has elapsed.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'quotaPacingUtilizationThresholdPercent',
    label: 'Quota pacing: usage threshold (%)',
    description: 'Start an early warning once usage reaches this percentage of a known quota window.',
    type: 'number',
    category: 'advanced',
    min: 0,
    max: 100,
  },
  {
    key: 'quotaPacingLatestElapsedPercent',
    label: 'Quota pacing: latest elapsed time (%)',
    description: 'Only warn when the quota window has used no more than this percentage of its time budget.',
    type: 'number',
    category: 'advanced',
    min: 0,
    max: 100,
  },
  {
    key: 'codebaseAutoIndexMaxFiles',
    label: 'Legacy index: skip folders over this many files',
    description:
      "Don't auto-run the legacy index on folders with more files than this. You can still index them manually.",
    type: 'number',
    category: 'advanced',
    min: 100,
    max: 1_000_000,
  },
  {
    key: 'codebaseAutoIndexMaxBytes',
    label: 'Legacy index: skip folders over this size (bytes)',
    description:
      "Don't auto-run the legacy index on folders whose files add up to more than this many bytes.",
    type: 'number',
    category: 'advanced',
    min: 1_048_576,
    max: 10 * 1024 * 1024 * 1024,
  },
  {
    key: 'codebaseAutoIndexConcurrent',
    label: 'Legacy index: runs at once',
    description:
      'How many folders the legacy index can process at the same time. Keep this at 1 — it is heavy.',
    type: 'number',
    category: 'advanced',
    min: 1,
    max: 4,
  },
  {
    key: 'codebaseAutoIndexDebounceMs',
    label: 'Legacy index: start delay (ms)',
    description:
      'Wait this long after a folder opens before starting the legacy index, to batch rapid folder switches into one run.',
    type: 'number',
    category: 'advanced',
    min: 0,
    max: 300000,
  },
  {
    key: 'codebaseAutoIndexStartupHint',
    label: 'Legacy index: run your last folder at launch',
    description:
      'When the app starts, run the legacy codebase index for the folder you used most recently.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'projectKnowledgeAutoMirrorEnabled',
    label: 'Build the Knowledge Graph when a folder opens',
    description:
      'Copy code structure into the project Knowledge Graph as soon as you open a folder, so the Knowledge view has data without running an agent first.',
    type: 'boolean',
    category: 'advanced',
  },
  {
    key: 'projectKnowledgeAutoMirrorDebounceMs',
    label: 'Knowledge Graph: start delay (ms)',
    description:
      'Wait this long after a folder opens before updating the Knowledge Graph, to batch rapid folder switches into one update.',
    type: 'number',
    category: 'advanced',
    min: 0,
    max: 300000,
  },
  {
    key: 'projectKnowledgeAutoMirrorMaxConcurrent',
    label: 'Knowledge Graph: updates at once',
    description:
      'How many folders can update the Knowledge Graph at the same time.',
    type: 'number',
    category: 'advanced',
    min: 1,
    max: 4,
  },
  {
    key: 'projectKnowledgeAutoMirrorSkipWithinMs',
    label: 'Knowledge Graph: skip-if-recent window (ms)',
    description:
      'Skip the automatic update if the Knowledge Graph was already refreshed within this window. Manual refreshes always run.',
    type: 'number',
    category: 'advanced',
    min: 0,
    max: 3600000,
  },
  {
    key: 'projectKnowledgeAutoMirrorStartupHint',
    label: 'Knowledge Graph: build your last folder at launch',
    description:
      'When the app starts, build the Knowledge Graph for the folder you used most recently.',
    type: 'boolean',
    category: 'advanced',
  },
];
