/**
 * S2.1 — every setting declares HOW it surfaces, so "this key has no UI" is a
 * decision on the record rather than an oversight.
 *
 * The gap this closes, measured: `AppSettings` has 190 keys and
 * `SETTINGS_METADATA` covered 126 of them. The other 64 had no declaration
 * anywhere — not hidden, not internal, just absent, and nothing failed.
 *
 * The `satisfies Record<keyof AppSettings, SettingSurfacing>` below is the
 * load-bearing part: adding a key to `AppSettings` now fails to compile until
 * someone classifies it. That is the difference between a list that happens to
 * be complete today and one that cannot silently rot.
 *
 * The classifications are derived from how each key ACTUALLY surfaces today,
 * not from how anyone thinks it should:
 *  - `tab`      — has metadata and appears in a category-driven tab.
 *  - `bespoke`  — has metadata but is marked `hidden`, meaning a dedicated tab
 *                 owns it and selects it by explicit key (see `hidden` in
 *                 `settings-metadata.types.ts`).
 *  - `internal` — no metadata: not user-editable through the settings UI at
 *                 all. Many are legitimately internal (usage counters, learned
 *                 model memory, enrollment tokens, per-provider maps written by
 *                 other surfaces). Some are arguably missing UI. This registry
 *                 does not adjudicate that — it makes the set visible and
 *                 reviewable, which it was not before.
 *  - `hidden`   — reserved for a key deliberately withheld from every surface.
 *                 Nothing uses it yet; it exists so "withheld" and "has no UI"
 *                 stay distinguishable.
 */

import type { AppSettings } from './settings.types';

export type SettingSurfacing = 'tab' | 'bespoke' | 'hidden' | 'internal';

export const SETTING_SURFACING = {
  defaultYoloMode: 'tab',
  defaultWorkingDirectory: 'tab',
  defaultCli: 'tab',
  defaultModel: 'tab',
  defaultModelByProvider: 'internal',
  automationDefaultCli: 'internal',
  automationDefaultModel: 'internal',
  defaultFastMode: 'tab',
  defaultFastModeByProvider: 'internal',
  modelUsageByKey: 'internal',
  modelPickerFavorites: 'internal',
  residentClaudeSession: 'internal',
  contextEvidenceModeByProvider: 'internal',
  theme: 'tab',
  maxChildrenPerParent: 'tab',
  maxTotalInstances: 'tab',
  autoTerminateIdleMinutes: 'tab',
  allowNestedOrchestration: 'tab',
  maxSpawnDepth: 'tab',
  docReviewResumeOnSubmit: 'tab',
  defaultMissedRunPolicy: 'tab',
  outputBufferSize: 'tab',
  enableDiskStorage: 'tab',
  maxDiskStorageMB: 'tab',
  memoryWarningThresholdMB: 'tab',
  autoTerminateOnMemoryPressure: 'tab',
  persistSessionContent: 'tab',
  cumulativeTokenCompactionTrigger: 'tab',
  outputStyle: 'tab',
  fontSize: 'tab',
  displayDensity: 'tab',
  sidebarStyle: 'tab',
  contextWarningThreshold: 'tab',
  showToolMessages: 'tab',
  showThinking: 'tab',
  thinkingDefaultExpanded: 'tab',
  showCost: 'tab',
  maxRecentDirectories: 'tab',
  keybindingCustomizations: 'internal',
  customModelOverride: 'bespoke',
  customModelsByProvider: 'bespoke',
  modelCatalogRemoteOverrideUrl: 'tab',
  parserBufferMaxKB: 'tab',
  codememEnabled: 'tab',
  loopSurfaceCodemem: 'internal',
  loopSurfaceLessons: 'internal',
  codememIndexingEnabled: 'tab',
  codememLspWorkerEnabled: 'tab',
  codememPrewarmEnabled: 'tab',
  codememPrewarmMaxConcurrent: 'tab',
  codememPrewarmDebounceMs: 'tab',
  codememPrewarmStartupHint: 'tab',
  commandDiagnosticsAvailable: 'tab',
  broadRootFileThreshold: 'tab',
  chromeDevtoolsAttachEnabled: 'tab',
  chromeDevtoolsAttachProfileId: 'tab',
  browserVaultMasterPasswordFile: 'tab',
  browserVaultAutoUnlock: 'tab',
  browserAuxExtractionEnabled: 'internal',
  browserMcpToolDeferral: 'tab',
  sessionHandoffStateEnabled: 'tab',
  claudeFallbackModel: 'tab',
  claudeSubprocessEnvScrub: 'tab',
  memoryInstructionGate: 'tab',
  sessionFailoverProviders: 'tab',
  sessionFailoverMaxSwitches: 'tab',
  sessionFailoverOfferAfterMinutes: 'tab',
  instructionTrustGate: 'tab',
  browserAllowSharedTabCredentialFill: 'tab',
  workspaceSecretsEnabled: 'tab',
  workspaceSecretsAllowAgentRequests: 'tab',
  codebaseAutoIndexEnabled: 'tab',
  instanceProviderLimitResumeEnabled: 'tab',
  loopAllowProviderOverage: 'tab',
  quotaPacingWarningEnabled: 'tab',
  quotaPacingUtilizationThresholdPercent: 'tab',
  quotaPacingLatestElapsedPercent: 'tab',
  codebaseAutoIndexMaxFiles: 'tab',
  codebaseAutoIndexMaxBytes: 'tab',
  codebaseAutoIndexConcurrent: 'tab',
  codebaseAutoIndexDebounceMs: 'tab',
  codebaseAutoIndexStartupHint: 'tab',
  projectKnowledgeAutoMirrorEnabled: 'tab',
  projectKnowledgeAutoMirrorDebounceMs: 'tab',
  projectKnowledgeAutoMirrorMaxConcurrent: 'tab',
  projectKnowledgeAutoMirrorSkipWithinMs: 'tab',
  projectKnowledgeAutoMirrorStartupHint: 'tab',
  crossModelReviewEnabled: 'tab',
  crossModelReviewDepth: 'tab',
  crossModelReviewMaxReviewers: 'tab',
  crossModelReviewProviders: 'tab',
  crossModelReviewTimeout: 'tab',
  crossModelReviewTypes: 'tab',
  crossModelReviewModelByProvider: 'internal',
  loopModelByProvider: 'internal',
  crossModelReviewLocalEnabled: 'tab',
  crossModelReviewLocalSelectorId: 'tab',
  crossModelReviewLocalTimeout: 'tab',
  crossModelReviewLocalMaxToolRounds: 'tab',
  providersExcludedFromAutomation: 'tab',
  copilotAccountProfiles: 'bespoke',
  copilotAccountRoutingRules: 'bespoke',
  pingPongReviewerProvider: 'tab',
  pingPongMaxRounds: 'tab',
  voiceSttRoutingMode: 'internal',
  voiceLocalSttEnabled: 'internal',
  voiceLocalSttWorkerNodeId: 'internal',
  voiceLocalSttModel: 'internal',
  voiceLocalSttLanguage: 'internal',
  voiceThisDeviceSttEndpointUrl: 'internal',
  voiceThisDeviceSttApiKeyEnv: 'internal',
  voiceLocalSttMaxSegmentMs: 'internal',
  workerMode: 'internal',
  remoteNodesEnabled: 'internal',
  remoteNodesServerPort: 'internal',
  remoteNodesServerHost: 'internal',
  remoteNodesEnrollmentToken: 'internal',
  remoteNodesAutoOffloadBrowser: 'internal',
  remoteNodesAutoOffloadAndroid: 'internal',
  remoteNodesAutoOffloadGpu: 'internal',
  remoteNodesNamespace: 'internal',
  remoteNodesRequireTls: 'internal',
  remoteNodesTlsMode: 'internal',
  remoteNodesTlsCertPath: 'internal',
  remoteNodesTlsKeyPath: 'internal',
  remoteNodesRegisteredNodes: 'internal',
  thinClientWsEnabled: 'internal',
  thinClientWsHost: 'internal',
  thinClientWsPort: 'internal',
  mobileGatewayEnabled: 'internal',
  mobileGatewayPort: 'internal',
  mobileGatewayBindInterface: 'internal',
  mobileGatewayDevices: 'internal',
  mobileGatewayTlsCertPath: 'internal',
  mobileGatewayTlsKeyPath: 'internal',
  mobileGatewayApnsKeyP8: 'internal',
  mobileGatewayApnsKeyId: 'internal',
  mobileGatewayApnsTeamId: 'internal',
  mobileGatewayApnsBundleId: 'internal',
  mobileGatewayApnsProduction: 'internal',
  pauseFeatureEnabled: 'tab',
  pauseOnVpnEnabled: 'tab',
  pauseVpnInterfacePattern: 'tab',
  pauseTreatExistingVpnAsActive: 'tab',
  pauseDetectorDiagnostics: 'tab',
  pauseReachabilityProbeHost: 'tab',
  pauseReachabilityProbeMode: 'tab',
  pauseReachabilityProbeIntervalSec: 'tab',
  pauseAllowPrivateRanges: 'tab',
  mcpCleanupBackupsOnQuit: 'tab',
  mcpDisableProviderBackups: 'tab',
  mcpAllowWorldWritableParent: 'tab',
  graphClientId: 'tab',
  graphAuthority: 'tab',
  graphScopesJson: 'tab',
  graphAgentWritableAccountsJson: 'tab',
  rtkEnabled: 'tab',
  rtkBundledOnly: 'tab',
  notifyOnAgentCompletion: 'tab',
  notifyOnLoopTerminal: 'tab',
  notificationSoundMode: 'tab',
  notificationCooldownSeconds: 'tab',
  notificationQuietHoursEnabled: 'tab',
  notificationQuietHoursStartHour: 'tab',
  notificationQuietHoursEndHour: 'tab',
  channelToolHeartbeat: 'tab',
  cliUpdatePolicy: 'tab',
  injectRepoMap: 'internal',
  repoMapTokenBudget: 'internal',
  detectDegradedAdapterOutput: 'internal',
  toolLoopAutoInterrupt: 'internal',
  approvalAdjudicationEnabled: 'internal',
  enableSpawnWorkerOffload: 'internal',
  projectPluginTrust: 'internal',
  allowPrCreation: 'internal',
  auxiliaryLlmEnabled: 'internal',
  auxiliaryLlmRoutingMode: 'internal',
  auxiliaryLlmAllowRemoteWorkerModels: 'internal',
  auxiliaryLlmUseLocalhostOllama: 'internal',
  auxiliaryLlmDailySpendCapUsd: 'internal',
  auxiliaryLlmEndpointsJson: 'internal',
  auxiliaryLlmSlotsJson: 'internal',
  auxiliaryLlmQuickModel: 'internal',
  auxiliaryLlmQualityModel: 'internal',
  auxiliaryLlmRoutingClassificationEnabled: 'internal',
  localAiGuardDefaultFallbackPolicy: 'tab',
  localAiGuardDailyFallbackBudgetUsd: 'tab',
  localAiGuardConfirmAboveInputTokens: 'tab',
  orchestrationRoutingPolicyJson: 'internal',
  reactionsEnabled: 'tab',
  reactionsPollIntervalMs: 'tab',
  transcriptVirtualization: 'internal',

  // Inherited from `DesktopComputerUseSettings` rather than declared in the
  // `AppSettings` body — which is exactly why the first generated version of
  // this file missed them and the `satisfies` check caught it. All six are
  // owned by the dedicated Computer Use tab (S1.5).
  computerUseEnabled: 'bespoke',
  computerUseAllowedAppsJson: 'bespoke',
  computerUseDeniedAppsJson: 'bespoke',
  computerUseRequireApprovalForInput: 'bespoke',
  computerUseStoreScreenshotsForEscalations: 'bespoke',
  computerUseAutonomyLevel: 'bespoke',
} as const satisfies Record<keyof AppSettings, SettingSurfacing>;

/** Keys with no settings-UI presence at all. */
export function internalSettingKeys(): (keyof AppSettings)[] {
  return (Object.keys(SETTING_SURFACING) as (keyof AppSettings)[])
    .filter((key) => SETTING_SURFACING[key] === 'internal');
}
